### ISSUE TITLE
Android Broadcast detector will report on all broadcasts, even secure ones

### ISSUE THREAD

**Issue by jsotuyod** [find-sec-bugs/find-sec-bugs#117]
The [detector has no logic to distinguish between secure and insecure broadcasts](https://github.com/h3xstream/find-sec-bugs/blob/master/plugin/src/main/java/com/h3xstream/findsecbugs/android/BroadcastDetector.java). Suppressing the error once the issue is solved is the only way to silence it, but doing so ay introduce undetected regressions later on.

**Comment by h3xstream** [comment]
HI @jsotuyod,
Currently the broadcast rule is trigger for manual review. If your broadcast permission is properly configured `<permission android:name="my.app.PERMISSION" android:protectionLevel="signature"/>` or it is intend to be public notification, you can add the following annotation.

```java
import edu.umd.cs.findbugs.annotations.SuppressWarnings;

@SuppressWarnings(value="ANDROID_BROADCAST", justification="Signature validation was configured in the manifest.xml")`
public void methodWhereTheBroadcastIsDone() {
     //...
}
```

I will update the description of this bug instance to include this guidance.

**Comment by h3xstream** [comment]
If this next feature gets implemented, this feature request will be reopen.
https://github.com/findbugsproject/findbugs/issues/77
