### ISSUE TITLE
Running plugin via Gradle

### ISSUE THREAD

**Issue by mmoayyed** [find-sec-bugs/find-sec-bugs#134]
Are there examples to show how this library can be used via Gradle's findbugs plugin?

**Comment by h3xstream** [comment]
Not yet.
I could not found the support for plugins configuration.

Please open a question/feature request on the gradle forum : 
https://discuss.gradle.org/ ([Official issue tracker](http://gradle.org/development/))

**Comment by mmoayyed** [comment]
For some reason I am unable to actually create an issue, but I will post to the forums.

**Comment by mmoayyed** [comment]
https://discuss.gradle.org/t/findbugs-plugin-using-custom-libraries/13002

**Comment by h3xstream** [comment]
Thanks I will follow closely this thread. I will probably be the most common use case in Continuous Integration for Android projects.

**Comment by krishna-pandey** [comment]
I am able to integrate findsecbugs with Gradle. Please see the configuration below:

subprojects {
  apply plugin: 'java'
  apply plugin: 'findbugs'
  apply plugin: 'eclipse'
  apply plugin: 'maven'
  apply plugin: 'signing'

  sourceCompatibility = 1.7

  dependencies {
    findbugs 'com.google.code.findbugs:findbugs:3.0.0'
    findbugs configurations.findbugsPlugins.dependencies

    // Here we mention findsecbugs plugin
    findbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.2.0'
 }
  task findbugs(type: FindBugs) {

    classes = fileTree(project.rootDir.absolutePath).include("**/*.class");
    source = fileTree(project.rootDir.absolutePath).include("**/*.java");
    classpath = files()
    pluginClasspath = project.configurations.findbugsPlugins

    findbugs {
     toolVersion = "3.0.0"
     sourceSets = [sourceSets.main]
     ignoreFailures = true
     reportsDir = file("$project.buildDir/findbugsReports")
     effort = "max"
     reportLevel = "high"
     includeFilter = file("$rootProject.projectDir/include.xml")
     excludeFilter = file("$rootProject.projectDir/exclude.xml")
    }
  }

**Comment by krishna-pandey** [comment]
@mmoayyed Can you please test the above configuration, if it's working for you.

**Comment by mmoayyed** [comment]
Sure. Stay tuned please.

**Comment by mmoayyed** [comment]
I have the following defined:

```gradle
findbugs group: 'com.google.code.findbugs', name: 'findbugs', version: findbugsVersion
findbugs configurations.findbugsPlugins.dependencies
findbugsPlugins group: 'com.mebigfatguy.fb-contrib', name: 'fb-contrib', version: findbugsContribVersion
findbugsPlugins group: 'com.h3xstream.findsecbugs', name: 'findsecbugs-plugin', version: findbugsSecVersion
```

and:

```gradle
findbugs {
        toolVersion = "${findbugsVersion}"
        sourceSets = [sourceSets.main]
        ignoreFailures = true
        reportsDir = file("$project.buildDir/findbugsReports")
        effort = "max"
        reportLevel = "high"
        visitors = ["FindSqlInjection", "SwitchFallthrough"]
        omitVisitors = ["FindNonShortCircuit"]
        includeFilter = file("$rootProject.projectDir/findbugs-rules.xml")
    }
```

Rules are very simple:

```xml
<FindBugsFilter>
    <Match>
        <Confidence value="2"/>
        <Rank value="15"/>
        <Bug category="SECURITY,PERFORMANCE,MALICIOUS_CODE"/>
        <Package name="^org\.jasig\.cas.+" />
    </Match>
</FindBugsFilter>

```

The only difference is I have a `visitors = ["FindSqlInjection", "SwitchFallthrough"]`. Should I take that out?

**Comment by mmoayyed** [comment]
I attempted to add the following to a class to test:

```java
    private byte[] aa = new byte[];
....

    public byte[] hello() {
        return this.aa;
    }
```

I was expecting this to be tagged as a security issue, but I get no errors back.

**Comment by h3xstream** [comment]
@mmoayyed  Which rule are you trying to trigger?

Also, I am wondering are you using gradle for Java, Android, Scala or Groovy code project ?

**Comment by mmoayyed** [comment]
The rule that says "returning a mutable byte array is a security issue". I used to get that quite often with the maven plugin. 

This is all pure Java.

**Comment by h3xstream** [comment]
A complete demo and configuration example is now available in the demos repository: 
https://github.com/find-sec-bugs/find-sec-bugs-demos/tree/master/android-insecure-bank-v2

A Java project with Gradle configuration will come shortly..

**Comment by h3xstream** [comment]
Please follow the issue #143 for the complete documentation efforts

**Comment by h3xstream** [comment]
@krishna-pandey Two notes on your configuration.
 - You should be using the latest version of FindSecurityBugs for better coverage `1.4.4`
 - `reportLevel` should be at least set to medium. high include only the most critical stuff. low will include a lot informational rules.
