### ISSUE TITLE
More XXE coverage

### ISSUE THREAD

**Issue by h3xstream** [find-sec-bugs/find-sec-bugs#138]
Some XXE parser to look for..

Built-in:
- [x] [TransformerFactory](https://github.com/find-sec-bugs/find-sec-bugs/blob/d4a0e0763d9cee71613b0fe4f00fa687a1084272/plugin/src/main/java/com/h3xstream/findsecbugs/xml/TransformerFactoryDetector.java) Added by @MaxNad
- [x] XMLReader
- [x] [XMLStreamReader/XMLInputFactory](https://github.com/find-sec-bugs/find-sec-bugs/blob/34e55f862ad7ba4cfc06a0f8b53bac6fa8354d3c/plugin/src/main/java/com/h3xstream/findsecbugs/xml/XmlStreamReaderDetector.java)
- [x] Unmarshaller
- [x] XPathExpression
- [x] SAXTransformerFactory (TransformerFactory is already convered)

More example here : https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet

**Comment by mcwww** [comment]
DOMParser must be added to this list as well, it's not detected at the moment by FindSecurityBugs

**Comment by h3xstream** [comment]
@mcwww Is it oracle.xml.parser.v2.DOMParser (https://docs.oracle.com/cd/B14098_01/web.1012/b12024/oracle/xml/parser/v2/DOMParser.html)?

**Comment by h3xstream** [comment]
Two issues were created to cover the API that could not be integrate in 1.8.0 (#394, #395)

**Comment by ehats** [comment]
@h3xstream was support for Unmarshaller (or JaxbContext) ever implemented in the end? I couldn't find any references to it in the codebase.

**Comment by h3xstream** [comment]
@ehats Good point.. I might have forgotten something.

**Comment by h3xstream** [comment]
@ehats I have open #537
