### ISSUE TITLE
Need to be able to build find-sec-bugs myself

### ISSUE THREAD

**Issue by davewichers** [find-sec-bugs/find-sec-bugs#140]
I am aware of: https://github.com/find-sec-bugs/find-sec-bugs/wiki/Compiling, and that Travis-CI is used to build the project (https://travis-ci.org/find-sec-bugs/find-sec-bugs/builds). However, I'd like to be able to build it myself.

Normally, all you have to do is a git clone, and then run: "mvn clean install" to build something. But when I do that for find-sec-bugs I get the following errors. I tried the various options described under /Compiling, like running "mvn clean" first, then "mvn clean install", or running: "mvn clean test-compile", but both the install and test-compile options generate errors like those below. 

Can you explain to me how I can build it myself successfully?

Thanks, Dave
```
[INFO] 9 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Find Security Bugs root ............................ SUCCESS [  1.145 s]
[INFO] FindBugs Test Utility .............................. SUCCESS [  8.024 s]
[INFO] findsecbugs-plugin-deps ............................ SUCCESS [  1.556 s]
[INFO] Find Security Bugs Plugin .......................... FAILURE [  3.639 s]
[INFO] FindBugs Command Line Interface .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.544 s
[INFO] Finished at: 2015-12-11T09:28:07-05:00
[INFO] Final Memory: 33M/446M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (default-testCompile) on project findsecbugs-plugin: Compilation failure: Compilation failure:
[ERROR] /Users/dwichers/git/find-sec-bugs/plugin/src/test/java/testcode/Logging.java:[5,25] error: package java.util.function does not exist
[ERROR] /Users/dwichers/git/find-sec-bugs/plugin/src/test/java/testcode/sqli/Jdbc.java:[63,12] error: cannot find symbol
[ERROR] variable stmt of type Statement
[ERROR] /Users/dwichers/git/find-sec-bugs/plugin/src/test/java/testcode/sqli/Jdbc.java:[64,12] error: cannot find symbol
[ERROR] variable stmt of type Statement
[ERROR] /Users/dwichers/git/find-sec-bugs/plugin/src/test/java/testcode/sqli/Jdbc.java:[65,12] error: cannot find symbol
[ERROR] variable stmt of type Statement
[ERROR] /Users/dwichers/git/find-sec-bugs/plugin/src/test/java/testcode/sqli/Jdbc.java:[66,12] error: cannot find symbol
[ERROR] /Users/dwichers/git/find-sec-bugs/plugin/src/test/java/testcode/Logging.java:[38,50] error: cannot find symbol
[ERROR] class Logging
[ERROR] /Users/dwichers/git/find-sec-bugs/plugin/src/test/java/testcode/Logging.java:[39,67] error: cannot find symbol
[ERROR] class Logging
[ERROR] /Users/dwichers/git/find-sec-bugs/plugin/src/test/java/testcode/Logging.java:[40,14] error: no suitable method found for logrb(Level,String,String,ResourceBundle,String,String)
[ERROR] is not applicable
[ERROR] (actual argument ResourceBundle cannot be converted to String by method invocation conversion)
[ERROR] method Logger.logrb(Level,String,String,String,String,Object) is not applicable
[ERROR] (actual argument ResourceBundle cannot be converted to String by method invocation conversion)
[ERROR] method Logger.logrb(Level,String,String,String,String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] /Users/dwichers/git/find-sec-bugs/plugin/src/test/java/testcode/Logging.java:[41,14] error: no suitable method found for logrb(Level,String,String,ResourceBundle,String,Exception)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :findsecbugs-plugin
```

**Comment by arthepsy** [comment]
You need to use JDK8 (not JDK7) to compile find-sec-bugs.

**Comment by h3xstream** [comment]
@arthepsy is right.
The plugin is compile with Java 6 compatibility to support FindBugs 2 and legacy project. This might change soon or later.
The test classes however include samples with Java 8 API.

**Comment by davewichers** [comment]
Thank you. Using JDK8 helped alot, but I'm still stuck. I can now successfully run: mvn clean test-compile with no errors.

But when I run: mvn clean install

1) I get lots of warnings like:

|WARN | EasyBugReporter : Missing class javax.servlet.http.HttpServletRequestWrapper
|WARN | EasyBugReporter : Missing class javax.servlet.http.HttpServletRequest
|WARN | EasyBugReporter : Missing class testcode.xxe.util.PrintHandler
|WARN | EasyBugReporter : Missing class testcode.xpath.XmlUtils
etc.

2) More importantly, the build hangs with this as the last few lines of output:

New Bug Instance: [2]
  message=Dm: Found reliance on default encoding in testcode.xxe.XmlReaderVulnerable.main(String[]): String.getBytes()
  bugType=DM_DEFAULT_ENCODING  priority=High  category=I
  class=testcode.xxe.XmlReaderVulnerable  method=main  line=32
------------------------------------------------------
|WARN | EasyBugReporter : Missing class testcode.xxe.util.PrintHandler
|INFO | VerboseTestListener : <<<<<<<<<<<<<<<<<<<< Surefire test finished >>>>>>>>>>>>>>>>>>>>
STOPS HERE FOREVER AS FAR AS I CAN TELL

Any suggestions on how to fix this (or both issues)?   Thx

**Comment by davewichers** [comment]
False alarm!!! I just wasn't patient enough to wait. After giving it time I eventually get this. Not sure why it would take over 8 minutes ...

If there is something I can fix to make it faster and/or fix the warnings I mentioned, I'd like that.  Thx, Dave

[INFO] Reactor Summary:
[INFO] 
[INFO] Find Security Bugs root ............................ SUCCESS [  2.200 s]
[INFO] FindBugs Test Utility .............................. SUCCESS [ 14.798 s]
[INFO] findsecbugs-plugin-deps ............................ SUCCESS [  2.755 s]
[INFO] Find Security Bugs Plugin .......................... SUCCESS [08:21 min]
[INFO] Website Generator .................................. SUCCESS [  5.811 s]
[INFO] FindBugs Command Line Interface .................... SUCCESS [  1.203 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:48 min
[INFO] Finished at: 2015-12-11T15:00:28-05:00
[INFO] Final Memory: 77M/501M
[INFO] ------------------------------------------------------------------------

**Comment by h3xstream** [comment]
The "Missing class" warning is trigger in the test because the test samples have reference to other classes. The scan are done with specific classes being loaded. The analysis of the missing classes is not needed for the test cases.
We could theoretically add all the dependencies to the classpath to avoid those warning but that would not add much benefit.
If the warning would mention a sample class that is needed than the warning would be helpful. (We can not just hide the message for now.)

**Comment by h3xstream** [comment]
I added the requirements section otherwise somebody will also have the same problem : 
https://github.com/find-sec-bugs/find-sec-bugs/wiki/Compiling#requirements
