### ISSUE TITLE
[Documentation] - Add Table of Contents to Bug Patterns page

### ISSUE THREAD

**Issue by aabashkin** [find-sec-bugs/find-sec-bugs#160]
http://find-sec-bugs.github.io/bugs.htm please add a Table of Contents for easy browsing

Thanks

**Comment by h3xstream** [comment]
Makes sense

**Comment by aabashkin** [comment]
Perhaps we should also consider how to manage the complexity of this list in the long term. I'm sure it will keep growing.

Tags/Taxonomy of some sort?

**Comment by RichardBradley** [comment]
Fixed by #347

**Comment by h3xstream** [comment]
https://find-sec-bugs.github.io/bugs.htm

@RichardBradley : I finally updated the website.

**Comment by RichardBradley** [comment]
Thanks, looks good!
