### ISSUE TITLE
[Rule] - jQuery html() XSS

### ISSUE THREAD

**Issue by aabashkin** [find-sec-bugs/find-sec-bugs#161]
Using the jQuery html() method can lead to DOM XSS

`$('#myDiv').html('<script>alert("Hi!");</script>');`

Ref: http://www.w3schools.com/jquery/html_html.asp
Ref: https://www.box.com/blog/securing-jquery-against-unintended-xss/
Ref: http://stackoverflow.com/a/15928704

**Comment by dpnishant** [comment]
@aabashkin I'm not sure whether FSB has a Javascript parser.

**Comment by h3xstream** [comment]
@aabashkin FindBugs engine does not support the scanning of static files. I was planning to request this feature to the FindBugs team. If I do I will include a link in this ticket.

**Comment by h3xstream** [comment]
@aabashkin Maybe some day.. I already have a static analyser in Java that could be integrate.
https://sourceforge.net/p/findbugs/feature-requests/351/

**Comment by aabashkin** [comment]
Whenever I want to perform some quick static analysis in Java I usually look to this: https://github.com/tools4j/unix4j  . No need to learn everything all over again, it's just grep :+1: 

I took a look at the ticket you filed and voiced my support
