### ISSUE TITLE
Check that Play CSRF bypass is very strict

### ISSUE THREAD

**Issue by wsargent** [find-sec-bugs/find-sec-bugs#162]
There is a bypass faciliity in Play for some classes of CSRF, covered in http://semisafe.com/coding/2015/08/03/play_basics_csrf_protection.html -- the page explains what attackers should not be able to do under the model, but some users may prefer something stricter.

To ensure that CSRF is always applied, check for the config setting:

```
play.filters.csrf.header.bypass = false
```

You'll want to do this in a parsed Config, not a raw application.conf file, as it's only valid after parsing, which may involve several files and includes.

May also want to disable the bypass on content types such as `application/json` as well, by using a `whiteList` as described in the blog post.

**Comment by h3xstream** [comment]
This issue also depends on https://sourceforge.net/p/findbugs/feature-requests/351/

**Comment by HairyFotr** [comment]
I think findbugs issues are now tracked here: https://github.com/findbugsproject/findbugs

**Comment by h3xstream** [comment]
@HairyFotr Thanks ! That will save some time :)
