### ISSUE TITLE
Check for secure cookies in Play

### ISSUE THREAD

**Issue by wsargent** [find-sec-bugs/find-sec-bugs#165]
You want the following settings to be set to true in a secure system so that cookie information doesn't leak:

```
play.http.flash.secure=true
play.http.flash.httpOnly=true

play.http.session.secure=true
play.http.session.httpOnly=true

play.i18n.langCookieSecure=true
play.i18n.langCookieHttpOnly=true
```

**Comment by h3xstream** [comment]
If it's a configuration, FindBugs does not have the capability to look at static files.

**Comment by h3xstream** [comment]
The ticket will be reopen if FindBugs starts support static files that would allow the analysis of tha `application.conf``.
