### ISSUE TITLE
CustomInjection issues

### ISSUE THREAD

**Issue by dcsobral** [find-sec-bugs/find-sec-bugs#172]
- [x] Clearer documentation
 - [x] Support for files and resources
 - [x] Noisy error message

## 1. Clearer documentation

This is a mix of documentation and implementation issues. On the documentation side, no mention of `com/h3xstream/findsecbugs/injection/custom/CustomInjectionSource.properties` is made, though that resource is always loaded by default.

The error message produced when it isn't found points to the documentation, which seems to imply that no error message will be produced unless `findsecbugs.injection.sources` is set, or, alternatively, that no error message will be produced _if_ `findsecbugs.injection.sources` is set (the text is really unclear). Neither is the case, however.

So, the documentation should mention that the above file is always searched for and will always produce an error message if not found, and further that `findsecbugs.injection.sources` is used to provide _additional_ sources. It should also point out that multiple sources can be provided, something I only learned from the source code.

## 2. Support for files and resources

Second, `findsecbugs.injection.sources` searches _only_ for files. The findbugs plugin searches first for files then for resources, copying whatever it finds to the target directory for use, when configuring include and exclude filters. The checkstyle plugin does something similar, though the documentation suggests the order there is reversed. It would be really helpful if `findsecbugs.injection.sources` could be similarly configured, and documented.

## 3. Noisy error message

I'd rather `CustomInjectionSource` error message was omitted if `findsecbugs.injection.sources` is specified, as the documentation implies, so that one doesn't need to provide a file with `h3xstream`'s package path.

I'm putting all this in one ticket because the docs need to be changed in any case, and they need to be updated if any of the implementation is changed too.

**Comment by jqno** [comment]
I second this issue, and would like to add that the documentation at http://find-sec-bugs.github.io/bugs.htm#CUSTOM_INJECTION for the configuration itself, is a bit confusing, mainly because both examples don't seem to match. The first example is about `SqlUtil.execQuery`; the second seems to be about a method called `MySqlWrapper.executeQuery`.

In other words, I'm not sure what I specifically need to add to this properties file. Do I need to add methods where SQL strings are concatenated? Do I need to add methods that accept raw Strings with SQL statements, but don't necessarily concatenate them? (In the `SqlUtil.execQuery` example, both happen at the same place, but it doesn't necessarily have to be that way.)

Also, how do I know if I need to write `INVOKEVIRTUAL` or something else? What are my options here? I'm assuming the "index of the parameter injectable" is the position of the String parameter of the method in question, which is 0 in this case because it's the first and only parameter. But what is "Detector description to display"? In the example it says `CUSTOM_INJECTION` but what are my options there?

**Comment by formanek** [comment]
Besides improving documentation, I think we could start using the new format (which injection detectors use in `injection-sinks` configuration) for custom injections too. It is simpler and you don't need to know, what invoke instruction is used.

@jqno Using `INVOKEVIRTUAL`  or something else depends on whether the method is static, is from interface, is it constructor etc., you can also look into the generated bytecode. Index is a position started from 0 counted from the last parameter and double and long parameters are counted as two, so e.g. param _a_ in method `m(String a, long l)` has index 3. Parameter doesn't have to be String, but should be of supported types to make sense. Description to display specifies whether to report the bug as custom injection or directly as e.g. SQL injection together with other bugs of that type.

**Comment by jqno** [comment]
@formanek Reading all that, I agree with your suggestion to switch to the simpler format ;).

**Comment by dcsobral** [comment]
Index is counted from the *last* parameter? And doubles and long count
twice? Well, that would have been useful information...

On 1 March 2016 at 07:53, formanek <notifications@github.com> wrote:

> Besides improving documentation, I think we could start using the new
> format (which injection detectors use in injection-sinks configuration)
> for custom injections too. It is simpler and you don't need to know, what
> invoke instruction is used.
>
> @jqno <https://github.com/jqno> Using INVOKEVIRTUAL or something else
> depends on whether the method is static, is from interface, is it
> constructor etc., you can also look into the generated bytecode. Index is a
> position started from 0 counted from the last parameter and double and long
> parameters are counted as two, so e.g. param *a* in method m(String a,
> long l) has index 3. Parameter doesn't have to be String, but should be
> of supported types to make sense. Description to display specifies whether
> to report the bug as custom injection or directly as e.g. SQL injection
> together with other bugs of that type.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/find-sec-bugs/find-sec-bugs/issues/172#issuecomment-190754637>
> .
>



-- 
Daniel C. Sobral

I travel to the future all the time.

**Comment by h3xstream** [comment]
@jqno @dcsobral  https://github.com/find-sec-bugs/find-sec-bugs/wiki/Injection-detection

@formanek Don't hesitate to change the format to the readable order.

**Comment by h3xstream** [comment]
Status update.

@dcsobral I numbered your requests in the original.

2. It now test the path with first file based loading and than as a resource.
3. The warning is no longer present.
1. Documentation will be refactored soon.

**Comment by h3xstream** [comment]
ef312a87b3215d91db99d7717917482549756a01

The complete documentation will now be in the wiki : https://github.com/find-sec-bugs/find-sec-bugs/wiki/Custom-signatures
