### ISSUE TITLE
No plugin support for findbugs4sbt

### ISSUE THREAD

**Issue by jfeenstra** [find-sec-bugs/find-sec-bugs#181]
We want to use 'Find Security Bugs' in our SBT project (Scala with Play). Currently there seems to be no support for adding plugins to findbugs (like for Gradle: https://github.com/find-sec-bugs/find-sec-bugs/wiki/Gradle-configuration).

We're using 
plugins.sbt: ("de.johoop" % "findbugs4sbt" % "1.4.0")
build.sbt: import de.johoop.findbugs4sbt.FindBugs._

Will findbugs4sbt add pluginsupport or support for find-sec-bugs in the near future or is there another way to add find-sec-bugs support to SBT?

Thanks!

**Comment by mkienenb** [comment]
@jfeenstra  You'd need to ask that question at the findbugs4sbt project.

I don't know SBT or Scala, but it looks like all you'd need to do is clone each part of the code referencing classpath  and rename "[Cc]lasspath" to "[Pp]luginList" in the duplicated code in https://github.com/sbt/findbugs4sbt/blob/master/src/main/scala/de/johoop/findbugs4sbt/Settings.scala and other related files.   The handling of pluginList argument should be identical to the handling of the classpath argument.

**Comment by h3xstream** [comment]
@mkienenb is right.

You can follow the issue here : https://github.com/sbt/findbugs4sbt/issues/3
If you have an example with a workaround, let me know. I will documented it in the demos repository.

**Comment by jfeenstra** [comment]
Thanks for your response. I will take a look to it and update when we found a solution.
