### ISSUE TITLE
Gradle plugin for easier integration

### ISSUE THREAD

**Issue by mcandre** [find-sec-bugs/find-sec-bugs#183]
Could we publish a plugin to make it easy for gradle projects to add find-sec-bugs to their FindBugs setup?

**Comment by h3xstream** [comment]
I think that adding option to the existing Gradle plugin (findbugs-plugin) would be the best option.
Creating an additional plugin for Gradle would mean extra maintenance work.

Currently, the creation of a task that include FindBugs is the "recommended" configuration.
But I agree the configuration could be smaller for a quite common task

**Comment by mcandre** [comment]
> adding option to the existing Gradle plugin (findbugs-plugin) would be the best option.

+1

**Comment by h3xstream** [comment]
I am labeling this issue as won't fix because, I don't plan to extend the Gradle plugin at this point.

**Comment by topolik** [comment]
Some notes, if you find it useful :)

For me FindBugs gradle task works find with the `findbugsPlugins` dependency to findsecbugs-plugin (the gradle build file: https://github.com/topolik/liferay-portal/commit/0c9b1f5560941a718028babbc5d0c7ae5871f2e3)

However, there is one big drawback - FindBugs gradle task creates a new JVM process but doesn't transfer system properties. This is a big deal for taint analysis tuning. 

If you need this here is a improvement (for gradle 3.0 with no response from gradle community so far :( ): https://github.com/topolik/gradle/commit/01005363440958f025b340585654f2aa7e8fc353
