### ISSUE TITLE
find-sec-bugs in sonar to scan scala bytecode

### ISSUE THREAD

**Issue by kknd22** [find-sec-bugs/find-sec-bugs#186]
since findbug is using bytecode to do the scan, it should be able to scan the scala bytecode. Anyone know how to configure it in sonar to scan scala bytecode? Thanks

**Comment by h3xstream** [comment]
It's on my personal roadmap. I am hoping to get this integration by the end of the year.

**Comment by xeno6696** [comment]
Question:  Scala runs on the JVM right?  Isn't it all bytecode?

**Comment by kknd22** [comment]
correct and correct. The problem is that it dose not show the security issue at all  (used the same problematic java code in a scala file)

**Comment by kknd22** [comment]
@h3xstream thanks for the comment - for now, does it detect any scala generated byte code which have the same issue as java counter part at all?
-cl

**Comment by kknd22** [comment]
I have created a gradle project to figure out what find-sec-bugs can handle scala bytecode.

https://github.com/kknd22/sonar-gradle-mixed-multiple-project/tree/find-sec-bug-test

(notice the it is not on the master, but on the "find-sec-bug-test" branch )
./gradlew findSecurityBug
then check the findbug report under the build.
So far the results are: for java source, find-sec-bug does the job, for the counter part scala code, it reports nothing.

**Comment by kknd22** [comment]
By change reportLevel = "low" in the scala project, I was able to see the violation in the report.
So the gradle build is cool. So the sole question is on sonar now, which missed all scala problems

**Comment by h3xstream** [comment]
@kknd22 
The feature is officially planned in the respective Sonar-FindBugs project:
https://github.com/SonarQubeCommunity/sonar-findbugs/issues/28
