### ISSUE TITLE
XML parsing vulnerable to XXE (XMLReader) shortage

### ISSUE THREAD

**Issue by rebse** [find-sec-bugs/find-sec-bugs#191]
Despite having the Find Bugs rules :

Security - XML Parsing Vulnerable to XXE (DocumentBuilder)
Security - XML Parsing Vulnerable to XXE (SAXParser)
Security - XML Parsing Vulnerable to XXE (XMLReader)

activated in Sonarsource, preventing a XXE attack by unmarshalling from an XMLStreamReader that has the IS_SUPPORTING_EXTERNAL_ENTITIES and/or XMLInputFactory.SUPPORT_DTD properties
set to false is not included, f.e.
```
public String parseXML(InputStream input, XMLStreamReader r) {
 StringBuilder content = new StringBuilder();
 XMLInputFactory factory = XMLInputFactory.newFactory();
 factory.setProperty(XMLInputFactory.IS_SUPPORTING_EXTERNAL_ENTITIES, true);
 factory.setProperty(XMLInputFactory.SUPPORT_DTD, true);
 XMLStreamReader reader = r;
```
should raise two issues, because the properties from XMLInputFactory are both set true, but there are
no issues created, see a good explanation [at Stackoverflow](http://stackoverflow.com/a/12978808)

Regards, Gilbert

**Comment by rebse** [comment]
P.S. : see also [OWASP XXE Prevention Cheat Sheet ](https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#StAX_and_XMLInputFactory)

**Comment by h3xstream** [comment]
I have added XMLStreamReader to #138

**Comment by h3xstream** [comment]
I have create two vulnerable samples..
 - With default value (no interaction with the factory)
 - When the support is explicitly enable.

**Comment by h3xstream** [comment]
This detector will be available in the next release..
