### ISSUE TITLE
Release version 1.4.6

### ISSUE THREAD

**Issue by h3xstream** [find-sec-bugs/find-sec-bugs#195]
Priority:
 - [x] Deploy a new version on the Sonatype repository
 - [x] Update the website
 - [x] Package the CLI
 - [x] Publish release note

Others upstream projects to update
 - [x] Jenkins https://github.com/jenkinsci/findbugs-plugin/pull/11
 - [x] SonarSource
 - [x] IntelliJ https://github.com/andrepdo/findbugs-idea/pull/156
 - [x] OWASP Benchmark

**Comment by arthepsy** [comment]
FYI, `findsecbugs.sh` in cli package contains invalid reference to plugin version 1.4.5 not 1.4.6.

**Comment by h3xstream** [comment]
@arthepsy Ouch. Thanks

Package updated.
