### ISSUE TITLE
not to report null-porter dereference if there is code already throws RuntimeError

### ISSUE THREAD

**Issue by fredxc** [find-sec-bugs/find-sec-bugs#197]
I am trying the maven plugin for a scala project with Maven plugin, here is the version:
        <dependency>
            <groupId>com.h3xstream.findsecbugs</groupId>
            <artifactId>findsecbugs-plugin</artifactId>
            <version>1.4.6</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>findbugs-maven-plugin</artifactId>
            <version>3.0.3</version>
        </dependency>

There are scenarios that our codes throw our own checked error whereas an value is expected by the scanner, thus FindSecBugs reported a null ptr problem. if a runtime error/exception is already triggered on the line being reported, would it be better not report or make it special and configurable ? suppressing the bug type on every line or ignoring that rule does not seem an ideal or practical approach.  

Thank,
-fredxc.

**Comment by h3xstream** [comment]
Please provide a code sample.
I would also need a reference to the Bug being trigged.

It look like you are refering to a FindBugs rule (bug instance) not FindSecBugs (Security only bugs).

**Comment by fredxc** [comment]
You are right, this indeed is a rule from FindBugs general bugs. Run with intellij plugin 1.0.0 (I understand it may not be same as the maven plugin), I get this rule reference:

Problem classification:
Correctness (Null pointer dereference)
NP_ALWAYS_NULL (Null pointer dereference)
Notes:
Dereferenced at KRCRDecommissionReportDomainGenerator.scala:[line 43]
FindNullDeref (NP|RCN)
