### ISSUE TITLE
How to set findsecbugs.taint.customconfigfile through gradle?

### ISSUE THREAD

**Issue by michael-apptornado** [find-sec-bugs/find-sec-bugs#215]
Hi,

I'm trying to add find-sec-bugs to our gradle build. In our (eclipse) find-sec-bugs configuration, we make use of a custom config file to fine-tune the taint analysis. For eclipse, I could make find-sec-bugs pick that custom-config file up by adding `-Dfindsecbugs.taint.customconfigfile=filelocation` to the jvm arguments.

For gradle, I get the find-sec-bugs plugin to execute fine, except that I cannot find a way to configure the  `findsecbugs.taint.customconfigfile` system property. So far, I've tried the following:
- add `-Dfindsecbugs.taint.customconfigfile=filelocation` to the gradle commandline
- add `systemProp.findsecbugs.taint.customconfigfile=filelocation` to `gradle.properties`

While these things do add the corresponding system property to the project, the property does not seem to propagate to the final findbugs worker. I guess the problem is that this findbugs worker runs in an own jvm (?). I also could not find anything in the find-bugs plugin (https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.FindBugs.html) that would allow me to pass on a system property. 

Is there a way to set a custom config file location in a gradle build?

Thanks,

Michael

**Comment by h3xstream** [comment]
The configuration should be possible in the next release.
Thanks to @topolik this is include in this PR #214

**Comment by michael-apptornado** [comment]
That's good news. Thanks!

**Comment by michael-apptornado** [comment]
Looking at the pull request, and in particular the new `loadFromSystem()` method, I see that the change currently tries to lookup environment variables containing period characters, like `findsecbugs.taint.customconfigfile` (https://github.com/topolik/find-sec-bugs/blob/0498c65ec4d6ad7d551e3eda3120decfa82acd41/plugin/src/main/java/com/h3xstream/findsecbugs/FindSecBugsGlobalConfig.java#L52). 

I know that environment variables containing periods (i.e. `.`) can be quite a pain on linux (see e.g. http://unix.stackexchange.com/questions/93532/exporting-a-variable-with-dot-in-it). It seems spring is working around these problems by additionally checking for the corresponding variable name using underscores instead of periods as pointed out by Aleksandr Dubinsky on stackoverflow (http://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names#comment58762296_2821043; see also the corresponding source https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/env/SystemEnvironmentPropertySource.java). I wonder whether it might be a good idea to also do something like that in find-sec-bugs?

**Comment by topolik** [comment]
Hi @michael-apptornado, that's an interesting point! I send a new PR for that.

Locally I used this [patch for gradle 3.0](https://github.com/topolik/gradle/commit/16417600652353fbb92c9d048011124000988328), which can be another solution meanwhile

**Comment by topolik** [comment]
Haha, just saw https://github.com/find-sec-bugs/find-sec-bugs/pull/217 :smile:

**Comment by h3xstream** [comment]
#217 was merged
