### ISSUE TITLE
Changes to the Taint Analisys engine for Scala classes

### ISSUE THREAD

**Issue by MaxNad** [find-sec-bugs/find-sec-bugs#222]
Hi @formanek & @h3xstream 

I was working on a Scala SQLi detector and I found a few problems with the taint analysis for Scala.
1. Scala uses some objects to represent Null values.
   For instance, the GETSTATIC scala/collection/immutable/Nil$.MODULE$ : Lscala/collection/immutable/Nil$; instruction is used to push an object representing a null list on the stack. The taint detector doesn't recognize this item as Null and this can lead to false positives.

I thought about adding a taint-config file listing such objects and handling them in a visitGETSTATIC method.
1. Scala has a method naming convention that is not recognized by the regex used in the taint analysis.

Ex. of unrecognized invoke instruction : anorm/package$SqlStringInterpolation$.SQL$extension(Lscala/StringContext;Lscala/collection/Seq;)Lanorm/SimpleSql;

Current Class Regex : ([a-z][a-z0-9]_\/)_[A-Z][a-zA-Z0-9\$]*
Could be change to : ([a-z][a-z0-9]_\/)_(package|[A-Z])[a-zA-Z0-9\$]*

Current Method Regex : (([a-zA-Z][a-zA-Z0-9]_)|(<init>))
Could be change to : (([a-zA-Z][a-zA-Z0-9]_(\$extension)?)|(<init>))

I just wanted to have your opinion on this before I start changing things into the taint analysis.

**Comment by h3xstream** [comment]
@MaxNad I have no problem with this change of regex.
