### ISSUE TITLE
FP: sending local broadcasts via LocalBroadcastManager

### ISSUE THREAD

**Issue by luc-lynx** [find-sec-bugs/find-sec-bugs#224]
Such piece of code 

```
LocalBroadcastManager.getInstance(getActivity()).sendBroadcast(intent);
```

causes a false positive alert "Broadcast intents could be received by a malicious application", but the code actually sends local broadcast that can't be sniffed by other applications.

**Comment by MaxNad** [comment]
I do think the LocalBroadcastManager is safe to use.

https://developer.android.com/reference/android/support/v4/content/LocalBroadcastManager.html
    → "You know that the data you are broadcasting won't leave your app, so don't need to worry about leaking private data."

**Comment by h3xstream** [comment]
This enhancement was fully implemented by @MaxNad.

**Comment by luc-lynx** [comment]
Thanks!
