### ISSUE TITLE
sonar integration

### ISSUE THREAD

**Issue by javixeneize** [find-sec-bugs/find-sec-bugs#233]
Hi

How should this be integrated with Sonar? I have already findbugs plugin (http://docs.sonarqube.org/display/SONARQUBE45/FindBugs+Plugin)

Thanks

**Comment by h3xstream** [comment]
Update to the latest version of the FindBugs Plugin. It comes with FindBugs core rules **and** FindSecurityBugs rules.
You can pick and choose the rules that you need to verify but, most enterprise will use the predefined profiles (FindBugs Security Minimal or FindBugs Security Audit).

If you are a developper that want to be alert on critical alert only, choose FindBugs Security Minimal.
If you are part of a security team or need to do more indept analysis, you can turn on FindBugs Security Audit.

**Comment by xeno6696** [comment]
The Sonar plugin is already distributed with "find security bugs." That
said, releases are usually way behind.  The only way to make sure "find
security bugs" is updated for sonar, is to clone the sonar findbugs source
and manually compile that project with a more recent instance of "find
security bugs."

**Comment by h3xstream** [comment]
@xeno6696 I will try to prepare the master branch of sonar-findbugs with "bleed edge" versions. This way power user like you will be able to build and test the latest update.

**Comment by javixeneize** [comment]
Sounds good!

I have installed the latest version, and it doesnt seem to work properly
with SonarQube 6.1. I have an error stating that 0 files have been indexed.
Any idea about why could it be happening?

Properties files is as follows:

# Required metadata
sonar.projectKey=java-findbugs
sonar.projectName=Java :: findbugs
sonar.projectVersion=1

# Comma-separated paths to directories with sources (required)
sonar.sources=test
sonar.java.binaries=test/classes

# Language
sonar.language=java


# Encoding of the source files
sonar.sourceEncoding=UTF-8
