### ISSUE TITLE
findbugs not working with Sonarqube 6.1

### ISSUE THREAD

**Issue by javixeneize** [find-sec-bugs/find-sec-bugs#235]
Hi

I have installed the latest version, and it doesnt seem to work properly with SonarQube 6.1. I have an error stating that 0 files have been indexed. Any idea about why could it be happening? 

 Properties files is as follows: 
``` 
# Required metadata 
sonar.projectKey=java-findbugs 
sonar.projectName=Java :: findbugs
sonar.projectVersion=1 

#Comma-separated paths to directories with sources (required) 
sonar.sources=test
sonar.java.binaries=test/classes

 # Language
 sonar.language=java 

# Encoding of the source files 
sonar.sourceEncoding=UTF-8

**Comment by h3xstream** [comment]
It could be related to this : https://github.com/SonarQubeCommunity/sonar-findbugs/issues/51

But please create an issue in https://github.com/SonarQubeCommunity/sonar-findbugs.
