### ISSUE TITLE
How to integrate in Jenkins

### ISSUE THREAD

**Issue by linger118927** [find-sec-bugs/find-sec-bugs#237]
hello
 thank you for your find sec bugs，but i have a question
How to integrate in Jenkins，the jenkins only have FindBugs Plug-in and not find sec bugs
really thanks

**Comment by h3xstream** [comment]
- https://github.com/find-sec-bugs/find-sec-bugs/wiki/Jenkins-Tutorial
- https://github.com/find-sec-bugs/find-sec-bugs/wiki/Gradle-configuration#2-integration-procedure-of-findbugs-in-jenkins
