### ISSUE TITLE
Turbine SQL Injection

### ISSUE THREAD

**Issue by sdspbores** [find-sec-bugs/find-sec-bugs#238]
We use Apache Turbine which unfortunately allows the direct execution of SQL.

I was surprised that the following was not flagged by the plugin. Possibly I have the wrong expectations. Does the plugin detect string concatenation in the context of a likely SQL query?

```csharp
String sql = "SELECT * FROM " + args[0] + " WHERE ID=" + args[1];
BasePeer.executeQuery( sql );
```

**Comment by h3xstream** [comment]
API to look for : 
https://turbine.apache.org/turbine/turbine-2.1/apidocs/org/apache/turbine/om/peer/BasePeer.html

 - `BasePeer.executeQuery(***)`
 - `BasePeer.executeStatement(***)`

**Comment by sdspbores** [comment]
Forgot to mention, these interfaces are duplicated in the Apache Torque package as well.

https://db.apache.org/torque/torque-3.3/releases/torque-3.3/runtime/apidocs/org/apache/torque/util/BasePeer.html

**Comment by sdspbores** [comment]
Turbine and Torque provide Criteria objects and special retrieval methods that should be used instead. If these methods are not suitable, then use a java.sql.PreparedStatement instance directly.

			/* Unsafe */
			List< Record > records = BasePeer.executeQuery( "SELECT * FROM CUSTOMER WHERE ID=" + args[ 0 ] );

			/* Safe */
			Criteria c = new Criteria( );
			c.add( CustomerPeer.ID, args[ 0 ] );

			List< Customer > customers = CustomerPeer.doSelect( c );

			/*
			 * Also Safe
			 */
			Customer customer = CustomerPeer.retrieveByPK( new NumberKey( args[ 0 ] ) );

**Comment by h3xstream** [comment]
@sdspbores Perfect
