### ISSUE TITLE
CRLF injection CWE-117 does not detect request body parameters for jax-rs applications

### ISSUE THREAD

**Issue by OskarKjellin** [find-sec-bugs/find-sec-bugs#240]
Consider this code:

```java
@Path("/")
@POST
public Response postStuff(DataClass data) {
       logger.info("Got {}", data.stuff);
       return Response.ok().build();
}
```

This is still vulnerable to CRLF injection, but is not detected.

**Comment by h3xstream** [comment]
Pardon my lack of knowledge about logging API.

Is this Slf4j, logging, log4j or any other apis ?
If it is Slf4j, is it the behavior of a specific implementation (ie: logback) ?

I would be more tempt to report this as an issue to logback to enable auto-escaping of new line and other special characters..

**Comment by OskarKjellin** [comment]
I'm referring to the already existing feature that flags this:

```
@Path("/{id}")
@GET
public Response getStuff(@PathParam("id") String id) {
       logger.info("Got {}", id);
       return Response.ok().build();
}
```

But this is kind of a false positive because you cannot inject (as far as I've been able to find out) CRLF in path params. But you can easily in the body inject stuff as the example I posted first.

I'm referring to this feature #123 #125 #171 https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/main/java/com/h3xstream/findsecbugs/CrlfLogInjectionDetector.java

It is using slf4j, but the error isn't really specific to slf4j. Logging frameworks typically do not enforce this is newlines can be inserted as a "feature"

**Comment by h3xstream** [comment]
My perspective on this is that logback should have option (enable by default or not) to enforce escaping of new lines. I have the feeling that a minority of projects are concern about this vulnerabilities. If it is a concern, the only way to "take control" of this issue is automatic escaping with separation of logging message and dynamic parameters.
Basically, the same way SQL injection is a relatively easy to overcome if you are using prepare statement.

I tag the issue **[task]** to remind me to poke logback mailing list about this issue. I need to do some verifications to make sure what are the current settings available.

**Comment by OskarKjellin** [comment]
Not sure I really agree. There are many valid use cases to log new lines in msssages (stacktraces for instance). The issue becomes when you log "tainted" values. It already detects if you log tainted values but the process of the detecting it doesn't consider if you log a field of a tainted object, which I consider a bug...

**Comment by ptamarit** [comment]
Concerning automatic escaping of newlines with logback, there's the [OWASP Security Logging Project
](https://www.owasp.org/index.php/OWASP_Security_Logging_Project) doing this (I didn't give it a try yet). Maybe this should be mentioned in the bug description? Now I don't think that find-sec-bugs could automatically detect that a project is using this logger, so this rule would have to be disabled manually in this case. 

Concerning stacktraces, they're usually not sent to the logger as a string but as a `Throwable` (or `Exception`):

```
LOGGER.error("Exception when doing something", myException);
```

To be verified what the OWASP logger does, but it would make sense for it to escape the exception message(s) (which could contain some tainted user input), but not to escape the newlines separating each call in the stack.

**Comment by OskarKjellin** [comment]
Maybe I don't fully understand how find-sec-bugs work, but isn't the general taint detection process at fault? So this would be a missed SQL detection vulnerability:
```
@Path("/")
@POST
public Response postStuff(DataClass data) {
       sqlSelect("SELECT * FROM foo where id = '"+ data.stuff+"'");
       return Response.ok().build();
}

```

**Comment by h3xstream** [comment]
@ptamarit I have looked at [OWASP Security Logging Project
](https://www.owasp.org/index.php/OWASP_Security_Logging_Project) and it does not mention log injection. It seems to be focusing on logging HTTP requests.

@OskarKjellin Yes this is the case. The Logging are configured only to include the first argument.

I found the documentation I needed. Logback does provided configuration for automatic escaping. I does escaping for the complete message (not just argument of the string format).

Current plan:

 - [ ] Update the additional arguments in the sinks configurations
 - [ ] Improve the documentation to include and/or point to example of secure configuration.

**Configuration for logback**

http://logback.qos.ch/manual/layouts.html#replace

```java
<pattern>%replace(%msg){'\n', ' '}</pattern>
```

**Comment by h3xstream** [comment]
I'm postponing this to 1.7 because I don't have much time and I don't want to delay the release to much.

**Comment by h3xstream** [comment]
I have update the description for the logback directive.

**Comment by javabeanz** [comment]
https://github.com/javabeanz/owasp-security-logging/blob/master/owasp-security-logging-logback/src/main/java/org/owasp/security/logging/mask/CRLFConverter.java cleans logs of CRLF input

**Comment by h3xstream** [comment]
@OskarKjellin @jianli8 This is issue was a low priority. I don't consider log injection to be critical change compare to adding injection rules for example.
Nevertheless, I did some investigation. And the [SLF4J API added by @formanek](https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/main/resources/injection-sinks/crlf-logs.txt#L44-L93) do work as expected.

I will push my test and close this issue unless a different pattern is described.

**Comment by h3xstream** [comment]
Following the previous comment, all these new test cases catch CRLF injection: 
https://github.com/find-sec-bugs/find-sec-bugs/blob/ba3154c07cf5e3a403bf2a7adeb2aeabcc969409/plugin/src/test/java/testcode/logging/Slf4jSample.java#L7-L20

Make sure you allow LOW vulnerability to be reported. By default Medium and High are displayed.
