### ISSUE TITLE
Detect Commons lang Random utilities

### ISSUE THREAD

**Issue by h3xstream** [find-sec-bugs/find-sec-bugs#243]
The following APIs wrap random instances :

 - `org.apache.commons.lang.math.JVMRandom`
 - `org.apache.commons.lang.math.RandomUtils`

**Comment by formanek** [comment]
You can also add `org.apache.commons.lang.RandomStringUtils`, which could be used to generate predictable passwords or tokens (if the longest method signature and instance of SecureRandom is not used).

**Comment by h3xstream** [comment]
@formanek Good point.

`public static String random(int count, int start, int end, boolean letters, boolean numbers, char[] chars, Random random)` will likely be called when SecureRandom is passed. At some point, the developper will instantiate a Random class anyway if it is use insecurily.
