### ISSUE TITLE
Not getting the Find bug option

### ISSUE THREAD

**Issue by rajat007** [find-sec-bugs/find-sec-bugs#273]
I had import the project from Github URI in eclipse and then i need to the security testing of it at that time find bug option is not coming . I had checked that it is coming for the  other projects but with the project i am importing from git
![git](https://cloud.githubusercontent.com/assets/9781098/22417922/a4e035a6-e6fc-11e6-94f6-48266716d640.png)

**Comment by h3xstream** [comment]
Please follow this tutorial : https://github.com/find-sec-bugs/find-sec-bugs/wiki/Eclipse-Tutorial

**Comment by rajat007** [comment]
Thanks for the answer
I had followed the same tutorial but on right clicking the target folder i am not getting the option of Find Bug

**Comment by h3xstream** [comment]
Can you confirm that the plugin FindBugs is installed? Did you restarted Eclipse after the installation?

**Comment by rajat007** [comment]
Yes i had restarted also plugin , actually when i am clone the project from git using egit plugin in eclipse the project get stored in .git folder when i am opening the project saved under the git folder then the option of FindBug is not coming but when i am copying the same project and saving it in other folder then it is coming ?

will you please help me in this ?

**Comment by rajat007** [comment]
any update on it ?

**Comment by h3xstream** [comment]
Please test the tutorial on a fresh install of Eclipse. http://www.eclipse.org/downloads/packages/eclipse-ide-java-developers/marsr

**Comment by h3xstream** [comment]
I have updated the images of the tutorial. Images are now hosted in the hidden Git repo of the wiki.
https://github.com/find-sec-bugs/find-sec-bugs/wiki/Eclipse-Tutorial
I have taken the new screenshot based on a recent Eclipse installation (Eclipse Neon for Java Developpers)
