### ISSUE TITLE
Out of bounds mutables in ... (Assertion trigged)

### ISSUE THREAD

**Issue by h3xstream** [find-sec-bugs/find-sec-bugs#275]
## Code to reproduce

```java
public String someMethod(Bean someBean, String label) {
        Preconditions.checkArgument(SomeClass.CONSTANT_VALUE.equals(someBean.getStringValue2()) || SomeClass.CONSTANT_VALUE.equals(someBean.getStringValue2()));
        Preconditions.checkArgument(Validator.isValid(someBean.getStringValue1()));

        String parameters = Arrays.toString(someBean.getStringValue1().split(SomeClass.SEPARATOR)); //BOOM!
        [...]
```

## Error

The last line `Arrays.toString(...)` will trigger the assertion "Out of bounds mutables in someMethod"

## First troubleshooting

![ide](https://cloud.githubusercontent.com/assets/593130/23040865/e6814614-f460-11e6-8f4b-e77a331388e0.png)

## Refs

It could be the same issue where we never received a code sample to reproduce (#199).

**Comment by h3xstream** [comment]
To reproduce the bug : https://github.com/h3xstream/find-sec-bugs/commit/ab1ee4613e2dbbfb13ecef2a13f7abd6daf05eac

**Comment by h3xstream** [comment]
/cc @formanek, @topolik 
Any help would be welcome

I am unsure about the fix for this issue. It involve tainted mutable in the return value of a static method.

In the tested sample, the call to `Arrays.toString(Object[])` is static. There is only one argument needed. The return value will preserve the state (TAINTED, SAFE,..) of the original argument.

The stack look as follow when the transferTaintToMutable() is reach.
```
+============================
| [[ Stack ]]
| 0. UNKNOWN {U {split()}}
|============================
| [[ Local variables ]]
| null = U0[2] {[[?]+[?]]+[?]}
| null = U1[1] {[[?]+[?]]+[?]}
| null = U2[0] {[[?]+[?]]+[?]}
| null = U3 {[[?]+[?]]+[?]}
+============================
```

My conclusion is that the configuration should be change to : 
```
java/util/Arrays.toString([Ljava/lang/Object;)Ljava/lang/String;:0
```

## Generalisation

```
{{Method Signature}} :  {{Indexes that could be tainted}}  # {{Destination index that could become tainted}}
```

## Additional Validation

I am a big fan of automation so adding sanity check to config files would be great.

 - static method : index can be equal to the number of arguments minus 1.
 - instance method : index can be equal to the number of arguments (considering the instance reference to be on the stack)

**Comment by formanek** [comment]
@h3xstream You are right, [that configuration](https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/main/resources/taint-config/java-lang.txt#L185) is wrong. `#` shouldn't be present if only a new value is created and no existing is modified.

Any additional automatic validation could be useful, it's difficult not to make an error in hundreds of configuration instances and it would be helpful for people starting with custom configurations.
