### ISSUE TITLE
How could I report a Bug that not in a class

### ISSUE THREAD

**Issue by retanoj** [find-sec-bugs/find-sec-bugs#276]
I want to new a BugInstance to report a Bug about weak password in a config file.
I got the config file path, weak password location( source line number ), but I could not find a method of BugInstance to report a bug not in class.

This is not work:
`new BugInstance(this, WEAKPASSWORD_TYPE, Priorities.NORMAL_PRIORITY).addClass("")`

**Comment by h3xstream** [comment]
The best place to ask this new feature - at API level - would be the [SpotBugs project](https://github.com/spotbugs/spotbugs/issues/new).
(Find Security Bugs is a side-project)

**Comment by h3xstream** [comment]
Currently it is the big limitation of FindBugs/SpotBugs.
The best place to [ask for API enhancement would be the SpotBugs project](https://github.com/spotbugs/spotbugs/issues).

**Comment by retanoj** [comment]
@h3xstream Thx,  I will close this question.
