### ISSUE TITLE
New rule: detect https connections with weak SSL / TLS protocol

### ISSUE THREAD

**Issue by xsun12** [find-sec-bugs/find-sec-bugs#283]
Java by default uses SSL protocols or TLS 1.0 for outbound HTTPS connections. Both are insecure hence should be replaced by more secure TLS 1.2. Most developers are not careful enough to configure TLS protocol explicitly, hence there applications might be susceptible to man-in-the-middle attack.

Propose to add new rule to detect weak SSL / TLS protocols and recommend better practice.

I have 2 cases in mind:
1.  For applications using Apache HttpClient - detect the usage of [DefaultHttpClient ](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/DefaultHttpClient.html)and recommend [SystemDefaultHttpClient](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/SystemDefaultHttpClient.html)
1. For applications using [SSLContext ](http://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLContext.html)- detect the usage of "SSL" context and recommend "TLS" context

I can submit a pull request if this makes sense.

**Comment by h3xstream** [comment]
This make perfect sense. I did some comments in the PR.
