### ISSUE TITLE
Question about sinks file configuration

### ISSUE THREAD

**Issue by myronBob** [find-sec-bugs/find-sec-bugs#284]
![image](https://cloud.githubusercontent.com/assets/23491370/23732690/8cf9aa32-04af-11e7-9646-7e8ac4db358b.png)

I would like to know, what 's the meaning of the number in the red box, any help would be appreciated

**Comment by h3xstream** [comment]
It is normal to find it cryptic. 😄 

It represent the index of the arguments that are "injectable". The important part is to start counting from **the right side**.
The details are documented here : 
https://github.com/find-sec-bugs/find-sec-bugs/wiki/Injection-detection#sink-file-format

**Comment by myronBob** [comment]
Thanks a lot.
A little time ago, I tried to debug step by step and found the answer finally.
