### ISSUE TITLE
Make PREDICTABLE_RANDOM ignore Unit test classes? 

### ISSUE THREAD

**Issue by zolyfarkas** [find-sec-bugs/find-sec-bugs#295]
In my unit test cases I don't need a secure random, generates a lot of false positives, and I am not sure it is even worthwhile looking in the test classes...

**Comment by h3xstream** [comment]
You can exclude the test classes with a exclude filter file. http://findbugs.sourceforge.net/manual/filter.html

**exclude.xml**
```xml
<FindBugsFilter>
  <Match>
    <Class name="~.*Test$"/>
    <Bug category="SECURITY" />
  </Match>
</FindBugsFilter>
```

**Comment by zolyfarkas** [comment]
thanks
