### ISSUE TITLE
Sonarqube 6.3 compatibility?

### ISSUE THREAD

**Issue by javixeneize** [find-sec-bugs/find-sec-bugs#297]
Hi

Is this new version 1.6.0 (https://search.maven.org/remotecontent?filepath=com/h3xstream/findsecbugs/findsecbugs-plugin/1.6.0/findsecbugs-plugin-1.6.0.jar) compatible with sonarqube 6.3?

Thanks

**Comment by FrankS77** [comment]
Hello,

That interests me too. There is no Findbugs plugin to install in the Sonarqube plugins section. Should I manually install the Findbugs and find-sec-plugin or are all rules are now included in SonarJava? I see some security rules but not all.

Thanks

**Comment by h3xstream** [comment]
You can test this new release which is fully compatible with 6.3.
https://groups.google.com/forum/#!topic/sonarqube/WuRFaI-4L3A
