### ISSUE TITLE
Android SQL Injection

### ISSUE THREAD

**Issue by dawidppp** [find-sec-bugs/find-sec-bugs#302]
Hello,

I am trying to detect SQL Injection in an Android application. Sample code:
In _MainActivity_:
```java
	@Override
	protected void onCreate(Bundle savedInstanceState) {
	[...]
		mDbManager = new DbManager(this);
		btn.setOnClickListener(new OnClickListener() {
			@Override
			public void onClick(View v) {
				if (mDbManager.isCorrect(login.getText().toString(), pass
						.getText().toString())) {
					[...]
```
In _DbManager_ (extends _SQLiteOpenHelper_):
```java
	public boolean isCorrect(String login, String pass) {
	        String sql = "user = '" + login + "' AND pass = '" + HashFncHelper.calcMd5(pass) + "'";
	        Cursor c = db.query(TABLE_NAME, null, sql, null, null, null, null);
	        return c.moveToFirst();
	}
```
We can inject SQL, which is easily observed by entering the following login:
` ' or 1=1 --`
and authorization is bypassed. I did it on emulator.

So I try to detect it with **Find Security Bugs CLI**. I changed the script _./findsecbugs.sh_:
`java -Dfindsecbugs.taint.customconfigfile=android-sql-injection-sinks.txt -cp findbugs/\* edu.umd.cs.findbugs.LaunchAppropriateUI -pluginList plugins/findsecbugs-plugin-1.4.6.jar:plugins/noUpdateChecks.jar -include include.xml $@`
And now I try this command:
`./findsecbugs.sh -effort:max -longBugCodes -auxclasspath ~/Android/Sdk/platforms/android-23/  ~/app/`
and the file _android-sql-injection-sinks.txt_ looks as such:
`android/database/sqlite/SQLiteDatabase.query(Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Landroid/database/sqlite/Cursor;:0,1,2,4,6`

But it is not working. Find Security Bugs doesn’t find that bug. Why?

Link to the Android API:
https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html
Functions:
`query, queryWithFactory, rawQuery, rawQueryWithFactory`
I would like to test at least the `selection` argument in those functions.

**Comment by h3xstream** [comment]
I'm surprise we have not integrated those methods yet. 😲 

On the other hand, I will have to the test custom configuration myself. (I don't use this feature myself anymore.)

**Comment by topolik** [comment]
Hi @dawidppp,

just guessing.

`-Dfindsecbugs.taint.customconfigfile` is taint configuration, i.e. you can specify how the method modifies taint. 

What you are looking for is custom sinks file for  `SqlInjectionDetector`. Try
`-Dfindsecbugs.injection.customconfigfile.SqlInjectionDetector=android-sql-injection-sinks.txt|SQL_INJECTION_JDBC`

**Comment by dawidppp** [comment]
Hi @topolik,

I tried this:
`java -Dfindsecbugs.injection.customconfigfile.SqlInjectionDetector=android-sql-injection-sinks.txt|SQL_INJECTION_JDBC -cp findbugs/\* edu.umd.cs.findbugs.LaunchAppropriateUI -pluginList plugins/findsecbugs-plugin-1.4.6.jar:plugins/noUpdateChecks.jar -include include.xml $@`
Result:
`./findsecbugs.sh: line 1: SQL_INJECTION_JDBC: command not found`

I tried with backslash:
`java -Dfindsecbugs.injection.customconfigfile.SqlInjectionDetector=android-sql-injection-sinks.txt\|SQL_INJECTION_JDBC -cp findbugs/\* edu.umd.cs.findbugs.LaunchAppropriateUI -pluginList plugins/findsecbugs-plugin-1.4.6.jar:plugins/noUpdateChecks.jar -include include.xml $@`
And it was ok, but SQLI still not found.

I tried without that `|SQL_INJECTION_JDBC` - this same.

I found that:
https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/main/java/com/h3xstream/findsecbugs/injection/BasicInjectionDetector.java
and tried to show error. I tried with wrong file name and file with 'asdadasd'. Find Security Bugs CLI finished without error.
`-Dfindsecbugs.injection.customconfigfile.SqlInjectionDetector="android-sql-injection-sinks.txtSQL_INJECTION_JDBC"`
That ran without error too (without pipe).

**Comment by topolik** [comment]
Hi,

I think this was released as 1.5, you are using old version of the plugin.

Sorry, overlooked that for the first time.

**Comment by dawidppp** [comment]
I use:
https://github.com/find-sec-bugs/find-sec-bugs/releases/download/version-1.4.6/findsecbugs-cli-1.4.6.zip
from:
https://github.com/find-sec-bugs/find-sec-bugs/wiki/CLI-Tutorial

Now I see newer version in releases - 1.6. I will try it.

**Comment by h3xstream** [comment]
@dawidppp Would you mind sharing your method signature for Android SQL api?

**Comment by dawidppp** [comment]
Sorry for the late reply. I had another important project to do.

So, I downloaded Find Security Bugs CLI 1.6 and tried to run it like before.
I changed _./findsecbugs.sh_ (deleted `-quiet` and added `SqlInjectionDetector` as @topolik suggested) and ran it. Unfortunately the SQLI was still not found.
But when I tried it without pipe char, I got the following error:

> The following errors occurred during analysis:
>   Wrong injection config file definition: android-sql-injection-sinks.txtSQL_INJECTION_JDBC. Syntax: fileName|bugType, example: sql-custom.txt|SQL_INJECTION_HIBERNATE

 So it loaded the file...

@h3xstream:
Like I wrote in the first post, I use query method:
`	Cursor c = db.query(TABLE_NAME, null, sql, null, null, null, null);`
Which is described [here](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#query(java.lang.String,%20java.lang.String%5b%5d,%20java.lang.String,%20java.lang.String%5b%5d,%20java.lang.String,%20java.lang.String,%20java.lang.String)).

Is this what you had in mind?

**Comment by topolik** [comment]
@dawidppp, pipe is a special character for bash (and other shells): https://www.gnu.org/software/bash/manual/html_node/Pipelines.html

Try
* `-Dfindsecbugs.injection.customconfigfile.SqlInjectionDetector=android-sql-injection-sinks.txt\|SQL_INJECTION_JDBC`
* or java allows the value to be surrounded with quotation mark, i.e. `-Dfindsecbugs.injection.customconfigfile.SqlInjectionDetector="android-sql-injection-sinks.txt|SQL_INJECTION_JDBC"`

HTH.

**Comment by h3xstream** [comment]
@dawidppp I was thinking about the actual signature files.

**Comment by dawidppp** [comment]
@topolik 
My _findsecbugs.sh_ file:
`java -Dfindsecbugs.injection.customconfigfile.SqlInjectionDetector="android-sql-injection-sinks.txt|SQL_INJECTION_JDBC" -cp lib/\* edu.umd.cs.findbugs.LaunchAppropriateUI -pluginList lib/findsecbugs-plugin-1.6.0.jar -include include.xml $@`
So it's correct. I experimented with pipe to prove it's works and load the file.
I tried both. No error and no SQLI.

@h3xstream 
My current signature file (_android-sql-injection-sinks.txt_):
`android/database/sqlite/SQLiteDatabase.query(Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Landroid/database/sqlite/Cursor;:0,1,2,4,6`

**Comment by topolik** [comment]
@dawidppp Took me some time but found it.

(Hope @h3xstream won't complain I didn't give him the chance to solve it :) )

I downloaded android SDK and found your return type in the sink definition is not correct.

I usually use `javap` to get the correct signatures, for example:

`javap -s android/database/sqlite/SQLiteDatabase.class | sed $'s/.*public .* \([a-zA-Z0-9_]\+\)(.*/\\1/' | sed 's/.*descriptor: //' | tr '\n' '-' | sed 's/-(/(/g' | tr '-' '\n'` 

And it gives me (beside others):
```
query(Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Landroid/database/Cursor;
```

Please note it returns **`Landroid/database/Cursor;`**, you defined it with `Landroid/database/sqlite/Cursor;`.

----

So it works for me with this sink:
```
android/database/sqlite/SQLiteDatabase.query(Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Landroid/database/Cursor;:0,1,2,3,4,5,6
```

```
java -Dfindsecbugs.injection.customconfigfile.SqlInjectionDetector="project/sinks.txt|SQL_INJECTION_JDBC" -cp lib/\* edu.umd.cs.findbugs.LaunchAppropriateUI -pluginList findsecbugs-plugin-1.6.0.jar -auxclasspath /opt/android-studio/plugins/android/lib/layoutlib.jar project/TestAndroidSQL.class

H C NP: Null pointer dereference of ? in TestAndroidSQL.test(String)  Dereferenced at TestAndroidSQL.java:[line 6]
M S SECSQLIJDBC: This use of SQLiteDatabase.query(...) can be vulnerable to SQL injection  At TestAndroidSQL.java:[line 6]
Warnings generated: 2
```

Having:
```java

import android.database.sqlite.SQLiteDatabase;

public class TestAndroidSQL {
	public void test(String x) {
		SQLiteDatabase d = null;
		d.query(x, new String[]{x}, x, new String[]{x},x, x, x, x);
	}
}

HTH.

**Comment by h3xstream** [comment]
Yes. I was being lazy here about finding the signatures. 😄 

I notice that there are multiple APIs that can be injectable:

- SQLiteDatabase.query
- SQLiteDatabase.rawQuery
- SQLiteDatabase.execSQL

**Comment by dawidppp** [comment]
Oh my... @topolik - it works!
I changed only _android-sql-injection-sinks.txt_ file like you said. That's it!
I checked it in Android Studio and there is `Landroid/database/Cursor;` too.
Thank you very much :)

@h3xstream 
Yes, of course. I remember that.

**Comment by h3xstream** [comment]
I will integrate the signature to the main branch.. Anything is missing? @dawidppp 

## android/database/sqlite/SQLiteDatabase
```
android/database/sqlite/SQLiteDatabase.compileStatement(Ljava/lang/String;)Landroid/database/sqlite/SQLiteStatement;:0
android/database/sqlite/SQLiteDatabase.query(ZLjava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Landroid/database/Cursor;:0,1,2,3,5,7
android/database/sqlite/SQLiteDatabase.query(ZLjava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Landroid.os.CancellationSignal;)Landroid/database/Cursor;:1,2,3,4,6,8
android/database/sqlite/SQLiteDatabase.queryWithFactory(Landroid/database/sqlite/CursorFactory;ZLjava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Landroid/database/Cursor;:0,1,2,3,5,7
android/database/sqlite/SQLiteDatabase.queryWithFactory(Landroid/database/sqlite/CursorFactory;ZLjava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Landroid.os.CancellationSignal;)Landroid/database/Cursor;:1,2,3,4,6,8
android/database/sqlite/SQLiteDatabase.query(Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Landroid/database/Cursor;:0,1,2,4,6
android/database/sqlite/SQLiteDatabase.query(Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Landroid/database/Cursor;:0,1,2,3,5,7
android/database/sqlite/SQLiteDatabase.rawQuery(Ljava/lang/String;[Ljava/lang/String;)Landroid/database/Cursor;:1
android/database/sqlite/SQLiteDatabase.rawQuery(Ljava/lang/String;[Ljava/lang/String;Landroid.os.CancellationSignal;)Landroid/database/Cursor;:2
android/database/sqlite/SQLiteDatabase.rawQueryWithFactory(Landroid/database/sqlite/CursorFactory;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)Landroid/database/Cursor;:0,2
android/database/sqlite/SQLiteDatabase.rawQueryWithFactory(Landroid/database/sqlite/CursorFactory;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Landroid.os.CancellationSignal;)Landroid/database/Cursor;:1,3
android/database/sqlite/SQLiteDatabase.execSQL(Ljava/lang/String;)V:0
android/database/sqlite/SQLiteDatabase.execSQL(Ljava/lang/String;[Ljava/lang/Object;)V:1
```

## DatabaseUtils

```
android/database/DatabaseUtils.longForQuery(Landroid.database.sqlite.SQLiteDatabase;Ljava/lang/String;[Ljava/lang/String;)J:1
android/database/DatabaseUtils.stringForQuery(Landroid.database.sqlite.SQLiteDatabase;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;:1
android/database/DatabaseUtils.blobFileDescriptorForQuery(Landroid.database.sqlite.SQLiteDatabase;Ljava/lang/String;[Ljava/lang/String;)Landroid/os/ParcelFileDescriptor;:1
android/database/DatabaseUtils.createDbFromSqlStatements(Landroid.content.Context;Ljava/lang/String;ILjava/lang/String;)V:0

## DatabaseUtils : state transfer

```
android/database/DatabaseUtils.appendEscapedSQLString(Ljava/lang/StringBuilder;Ljava/lang/String;)V:0
android/database/DatabaseUtils.sqlEscapeString(Ljava/lang/String;)Ljava/lang/String;:0
android/database/DatabaseUtils.appendValueToSql(Ljava/lang/StringBuilder;Ljava/lang/Object;)V:
android/database/DatabaseUtils.concatenateWhere(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;:0,1
```

**Comment by dawidppp** [comment]
Wow, thanks @h3xstream. I think it is everything.
