### ISSUE TITLE
Gradle Integration for a Java Web Project

### ISSUE THREAD

**Issue by JonyKhatri123** [find-sec-bugs/find-sec-bugs#303]
I already have Findbugs in my gradle script for Java Web Project. I would like to integrate FindbugsSecurity in that gradle script.. I want only FindbugsSecurity and remove Findbugs .

Is there any way I can do it ?

**Comment by h3xstream** [comment]
This project has an example of Gradle configuration that focus on Security: 

https://github.com/find-sec-bugs/find-sec-bugs-demos/tree/master/android-insecure-bank-v2

The important parameter is : 
```groovy
        includeFilter = file("$rootProject.projectDir/fsb-include.xml")
```

**Comment by h3xstream** [comment]
I will assumed the question was answered. Let me know if this is not the case.
