### ISSUE TITLE
Can't resolve "Scala Play Server-Side Request Forgery (SSRF)"

### ISSUE THREAD

**Issue by jqno** [find-sec-bugs/find-sec-bugs#307]
I'm getting a `Scala Play Server-Side Request Forgery (SSRF)` issue on my Scala project, and I can't figure out how to resolve the issue.

We have a method that looks very much like the one in the report:

> ```scala
>def doGet(value:String) = Action {
>    WS.url(value).get().map { response =>
>        Ok(response.body)
>    }
>}
>```
> Solution/Countermeasures:
>
> * Don't accept request destinations from users
> * Accept a destination key, and use it to look up the target (legal) destination
> * White list URLs (if possible)
> * Validate that the beginning of the URL is part of a white list

However, no matter what I do with the `value` parameter (I've tried quite a few things), I keep getting the error. Even if I hard-code the url (`WS.url("https://www.google.com").get()`) the error still comes up.

How should I whitelist and/or validate the URL, as suggested in the countermeasures?

**Comment by MaxNad** [comment]
Hi,

If the hard-coded URL is triggering this detector, it is most likely an error from my part.
I can take a look at this, however, I am having problems recreating your issue.

I have created multiple test cases in the find-security-bugs-demo project and none of them gets flagged by the Scala SSRF Detector. You can see them in this branch of the [find-security-bugs-demo](https://github.com/MaxNad/find-sec-bugs-demos/tree/fsb_issue_307)

Could you please try to give me the Scala / Play versions you are using ?

**Comment by jqno** [comment]
We're using Scala 2.11.8 with Play 2.5.8. I see that you're demo project uses 2.4, so that might account for the issue. Some things have changed in the way `WS` works.

If it helps, I could create a demo project to reproduce the issue, probably tomorrow or so.

**Comment by MaxNad** [comment]
Hi jqno,

No need to create a sample project, I was able to reproduce your problem (it was indeed caused by the version difference).

It should now be fixed.
If you still have the problem while using the latest version (from source), do not hesitate to tell me.

Thanks for your help.

**Comment by jqno** [comment]
Hi!
Sorry for the slow reply, it took me a while to find the time to test this. I can report that it does indeed work in our project, however, it only works when I'm not also calling `withRequestTimeout` on the `WSRequest`, for some reason.

```scala
val request = wsClient.url("http://www.google.com")
request
  .withRequestTimeout(10000.millis)  // <- this line fails the SSRF check
  .get()
```

Is this intentional?

**Comment by MaxNad** [comment]
This is not intentional.

After looking into it, you will probably have this issue with all of the following calls :
`
      .withAuth([...])
      .withBody([...])
      .withFollowRedirects([...])
      .withHeaders([...])
      .withMethod([...])
      .withProxyServer([...])
      .withQueryString([...])
      .withRequestFilter([...])
      .withRequestTimeout([...])
      .withVirtualHost([...])`

I will look into it as soon as possible.

Thanks again for your help

**Comment by jqno** [comment]
Thanks! Let me know if/when I can test something for you.

**Comment by h3xstream** [comment]
Closing the issue it will be available in the next release.

**Comment by jqno** [comment]
The issue wasn't resolved yet, though.
I mean, you can still release (I'll just skip the version), but I still would like to have it fixed :).

**Comment by jqno** [comment]
Ah, that was fast :)

**Comment by MaxNad** [comment]
This commit should fix your issue.

Sorry for the delay, I was pretty busy in the last few days. That previous comment reminded me I had to do that :P

**Comment by jqno** [comment]
No worries, I appreciate the effort!
