### ISSUE TITLE
Taint Analysis works in tests, but not when packaged?

### ISSUE THREAD

**Issue by 4ndygu** [find-sec-bugs/find-sec-bugs#310]
Created a custom detector class to catch certain commands with taint analysis, like 

```java
public class X extends BasicInjectionDetector {

    public X(BugReporter bugReporter) {
        super(bugReporter);
        loadConfiguredSinks("X.txt", "COMMAND_INJECTION");
    }
    
    @Override
    protected int getPriority(Taint taint) {
        System.out.println(taint.)
        if (!taint.isSafe() && taint.hasTag(Taint.Tag.COMMAND_INJECTION_SAFE)) {
            return Priorities.IGNORE_PRIORITY;
        } else {
            return super.getPriority(taint);
        }
    }
}
```
And included it in findbugs.xml and messages.xml.

When I run this in tests, everything works fine. But when I run the package in Intellij against actual code, the test fails. I think it's something with regards to how I'm setting up the taint analysis, but all I've done is provision the new class and include it. Is there any potential misconfiguration I've done?

**Comment by 4ndygu** [comment]
Clarification: I'm porting find-sec-bugs to some custom server forms that use different functions than what is picked up by many of the default find-sec-bugs sink signatures. Namely, my sink is a "withHeader(string, string)" command that sits inside a configuration function of a server class that is drawn up. 

In my tests, my detector picks up the line of the potential vulnerability. But when I run and compile with mvn clean install, it only picks up a custom hard coded password detector which I wrote.

Thanks!

**Comment by h3xstream** [comment]
"When I run this in tests, everything works fine. " Is this unit tests like those in FSB ?

If the signature is ok with sample code, it should work in IntelliJ. You can verify that all the important classes are targeted by IntelliJ plugin. In the result view, 

Please provide a link to your fork/signature files.

**Comment by 4ndygu** [comment]
These are the unit tests in FSB. I'll paste the signature files soon.

**Comment by 4ndygu** [comment]
Ahh, totally my bad. It turns out I didn't format my XML correctly. Sorry for the bother!

**Comment by h3xstream** [comment]
@4ndygu  Thanks for the update.
