### ISSUE TITLE
Any way to tag specific input for taint sinks?

### ISSUE THREAD

**Issue by 4ndygu** [find-sec-bugs/find-sec-bugs#314]
Hi there,

I'm trying to identify function calls to a certain function, say, f1(String x, String y) where input is tainted, but only if, say, x = "cats". Is there any way I can crawl for this kind of granularity with my taint analysis? 

Currently, I'm identifying calls that go from some function header(String y) to sink(String x). I can get my Taint calls to trigger, but I'm having a hard time filtering for header() calls only when y is equal to some other certain String. I'm using the BasicInjectionDetector class for this functionality.

Thanks!

**Comment by h3xstream** [comment]
This detector could serve as an example.
https://github.com/find-sec-bugs/find-sec-bugs/tree/master/plugin/src/main/java/com/h3xstream/findsecbugs/injection/redirect

The source for the injection (sink) is need a small analysis that [verify that the parameter is "Location"](https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/main/java/com/h3xstream/findsecbugs/injection/redirect/RedirectionSource.java#L49) (`setHeader("Location", [...])`).

**Comment by 4ndygu** [comment]
Thanks! The detector for this class seems to inherit from the LegacyInjectionDetector, as opposed to the BasicInjectionDetector that's described here: https://www.ysofters.com/2015/08/31/taint-analysis-added-to-findbugs/. Is there a strong difference between the two?

**Comment by 4ndygu** [comment]
Just kidding, dig a little bit of digging and found out!

**Comment by h3xstream** [comment]
`LegacyInjectionDetector` is named Legacy because the method signature used to be hardcoded in the code.
Most of the detector where basically just a list of `if` matching similar pattern. David (@formanek) transform those implementation into configuration files. The only remaining classes building "Injection source" at runtime are special cases like yours.
