### ISSUE TITLE
Throwing custom tags onto injection points

### ISSUE THREAD

**Issue by 4ndygu** [find-sec-bugs/find-sec-bugs#315]
I'm trying to add a tag like this:

InsecureObject x = ....
x.safeSanitizeFunction()

It seems like the current tags, from what I'm seeing in android-taint-sql.txt, such as this example:
android/database/DatabaseUtils.appendValueToSql(Ljava/lang/StringBuilder;Ljava/lang/Object;)V:0|+SQL_INJECTION_SAFE

adds the SQL_INJECTION_SAFE tags when a potentially tainted parameter is passed into a configured function. Is there any way to call this tag when an object calls a function on itself? The example would be my example above. Thanks!

**Comment by h3xstream** [comment]
At the moment, their is no mechanism to add tag to instance this way.

**Comment by 4ndygu** [comment]
Sounds good.
