### ISSUE TITLE
Sonarlint integration

### ISSUE THREAD

**Issue by javixeneize** [find-sec-bugs/find-sec-bugs#336]
Hi

I am using sonarlint from my IDE, and i am referring to the project i have in the server that i have previously analysed using findsecuritybugs

However, the report generated by sonarlint only detects the vulnerabilities/bugs included in the default sonar rules

How can findsecuritybugs be integrated with sonarlint?

In short, i want sonarlint to analyse the code against the findescuritybugs rules that are in my sonar server

Thanks

**Comment by h3xstream** [comment]
SonarLint is not usefull for you.
SonarLint is a strategy from SonarSource to promote their rules. The best way they found is continuing their universal plugin SonarEclipse.

The best option at the moment is : https://github.com/sonar-intellij-plugin/sonar-intellij-plugin
It only load result from previous scan which is interesting to avoid the scanning time.

FindSecBugs can be used in IntelliJ directly with plugin: https://plugins.jetbrains.com/plugin/3847-findbugs-idea
It does not scale easily for large team but it is the quickest to get started. https://github.com/find-sec-bugs/find-sec-bugs/wiki/IntelliJ-Tutorial

**Comment by javixeneize** [comment]
Thanks Philippe

I want to have the same set of rules in my local IDE and in my sonar server. The best approach then is to use the findsecbugs plugin for intelliJ?

What about Eclipse? Any good alternative?

In any case, would it make sense to develop a plugin or similar that can do what sonarlint does, but against the set of rules of the sonar server?

Thanks

**Comment by h3xstream** [comment]
For a proper sync of the rules, I would say https://github.com/sonar-intellij-plugin/sonar-intellij-plugin is the best option.
Personnally once the scan is done on a CI (SonarQube), I would not run it in the IDE. I would simply browse the web interface. The navigation is decent and I can still investigate some case with my IDE.
