### ISSUE TITLE
Images on Gradle Configuration documentation page show 'Please update your account'

### ISSUE THREAD

**Issue by nwalsh1995** [find-sec-bugs/find-sec-bugs#337]
https://github.com/find-sec-bugs/find-sec-bugs/wiki/Gradle-configuration

It seems like Photobucket won't host content for third parties unless you specify it in your account settings. Not sure who 'owns' these files but they might want to enable that access for Photobucket, or just host the files elsewhere.

![image](https://user-images.githubusercontent.com/1879632/29693817-624f918e-88fd-11e7-9b40-faee48365331.png)

Clicking on the image and viewing it on Photobucket works as expected.

**Comment by h3xstream** [comment]
Thanks I have contact the original developer to obtain the images.
We will move those to the GitHub wiki repository.

**Comment by h3xstream** [comment]
Done! I found out that by clicking on PhotoBucket I can see the old images.
