### ISSUE TITLE
False possitives and filtering

### ISSUE THREAD

**Issue by javixeneize** [find-sec-bugs/find-sec-bugs#340]
Hi

Question about configuration of FindBugs/FindSecurityBugs in IntelliJ

1 - How can i mark something as false possitive in my IDE environment?
2 - How can i filter the issues? EG - I want only vulnerabilities reported

Thanks

**Comment by topolik** [comment]
Hi,

> 1 - How can i mark something as false possitive in my IDE environment?

I know about 3 options:
1. use filter files http://findbugs.sourceforge.net/manual/filter.html and configure them inside Settings -> Other Setttings -> FindBugs-IDEA
2. use `edu.umd.cs.findbugs.annotations.SuppressFBWarnings` annotation, you can choose your own one in the settings again
3. There is environment property `findsecbugs_taint_customconfigfile` that's used by many FindSecurityBugs detectors. You can use it to configure taint analysis like here (for example): https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/main/resources/taint-config/collections.txt My idea startup script:
```bash
#!/bin/bash

export findsecbugs_injection_customconfigfile_SqlInjectionDetector="liferay-config/liferay-SqlInjectionDetector.txt|SQL_INJECTION_HIBERNATE"
export findsecbugs_injection_customconfigfile_XssJspDetector="liferay-config/liferay-XssJspDetector.txt|XSS_JSP_PRINT"
export findsecbugs_injection_customconfigfile_XssServletDetector="liferay-config/liferay-XssServletDetector.txt|XSS_SERVLET"
export findsecbugs_taint_customconfigfile="liferay-config/liferay.txt"

export IDEA_VM_OPTIONS="$HOME/CloudData/linux-settings/idea64.vmoptions"

cd /opt/idea/
bash -x bin/idea.sh &
```

> 2 - How can i filter the issues? EG - I want only vulnerabilities reported

Again, inside Settings -> Other Setttings -> FindBugs-IDEA

----
Btw. github project for the IDEA plugin is here: https://github.com/andrepdo/findbugs-idea so try to ask there, maybe there are more ways.

**Comment by javixeneize** [comment]
Thanks. Its really what i wanted to hear :)

I have tried to use the sonarqube intellij plugin, but doesnt connect to the remote server. Looks like it is not supported anymore so it is not an option.

So,the solution i have to use is using both findsecurity bugs and sonarlint in my IDE to match the rules i have in the server.

Not sure if sonarlint plugin has a filtering option like this? Code smells are a real pain

Thanks

**Comment by topolik** [comment]
> Not sure if sonarlint plugin has a filtering option like this?

Sorry, I don't know.

**Comment by h3xstream** [comment]
For more info or feature requests regarding Sonar-Lint, the google group is more appropriate. https://groups.google.com/forum/#!forum/sonarqube
