### ISSUE TITLE
Identify XSS cause by ServletOutputStream.print()

### ISSUE THREAD

**Issue by bradflood** [find-sec-bugs/find-sec-bugs#341]
example code:
```java
/*
     * source=javax.servlet.ServletRequest.getParameter(java.lang.String):java.lang.String
     * sink=javax.servlet.ServletOutputStream.print(java.lang.String):void
*/
	
public static void writeRequestParametersToServletOutputStream_TraceFiltersFindThis(HttpServletRequest request, HttpServletResponse response) throws Exception {
	response.getOutputStream().print(request.getParameter("param"));
}
```

Sonar maven plugin 3.3.0.603
FindBugs 3.5.0
Find-Sec-Bugs 1.6.0
FB-contrib: 7.0.0

This vulnerability was identified by IBM AppScan as CWE-116.   Find-sec-bugs matches very closely with Appscan as we have it configured, except for CWE-116 issues.

**Comment by h3xstream** [comment]
It should be already detected.

**Comment by h3xstream** [comment]
Ok I got it !!

[ServletOutputStream](http://docs.oracle.com/javaee/6/api/javax/servlet/ServletOutputStream.html) is not configured in [xss-servlet.txt](https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/main/resources/injection-sinks/xss-servlet.txt)
