### ISSUE TITLE
Documentation: bug patterns page does not include the bug code

### ISSUE THREAD

**Issue by RichardBradley** [find-sec-bugs/find-sec-bugs#345]
If a bug is detected, the tool output looks something like:

`[INFO] Concatenating user-controlled input into a URL [my.app.SomeClass, my.app.SomeClass, my.app.SomeClass, my.app.SomeClass, my.app.SomeClass, my.app.SomeClass] At SomeClass.java:[line 109]At SomeClass.java:[line 103]At SomeClass.java:[line 104]At SomeClass.java:[line 105]At SomeClass.java:[line 106]At SomeClass.java:[line 107] HTTP_PARAMETER_POLLUTION`

The ["bugs" docs page](https://find-sec-bugs.github.io/bugs.htm) is the place to go for more info, but it doesn't currently contain the string `HTTP_PARAMETER_POLLUTION`, which makes it hard to search.

I would suggest adding the bug code to the section title for each bug description.

**Comment by h3xstream** [comment]
If you want to use internal Bug Pattern Id, use hashtag.

https://find-sec-bugs.github.io/bugs.htm#HTTP_PARAMETER_POLLUTION

**Comment by RichardBradley** [comment]
Fixed by #347
