### ISSUE TITLE
Detection of LogBack pattern for findsecbugs:CRLF_INJECTION_LOGS

### ISSUE THREAD

**Issue by creid31** [find-sec-bugs/find-sec-bugs#352]
We have code logging values that triggers this rule. `log.trace("saved message = {}", saved);`. Following the [suggestion](https://find-sec-bugs.github.io/bugs.htm#CRLF_INJECTION_LOGS) we added `<pattern>%-5level - %replace(%msg){'[\r\n]', ''}%n</pattern>` to our logback.xml in our project as seen below.

Is there a way to ensure that sonar/find-sec-bugs does not trigger on these lines when our logback has a pattern for it? We can mark the issues as resolved but I wanted to see if there was a way for it to be detected automatically instead.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

	<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>%-5level - %replace(%msg){'[\r\n]', ''}%n</pattern>
			<pattern>%d{HH:mm:ss.SSS} [%-5level] %logger{15} - %msg%n%rEx</pattern>
			<immediateFlush>false</immediateFlush>
		</encoder>
	</appender>

	<!-- Uncomment for logging ALL HTTP request and responses -->
	<!-- 	<logger name="io.gatling.http.ahc" level="TRACE" /> -->
	<!--    <logger name="io.gatling.http.response" level="TRACE" /> -->

	<!-- Uncomment for logging ONLY FAILED HTTP request and responses -->
	<!--<logger name="io.gatling.http.ahc" level="DEBUG" />-->
	<!--<logger name="io.gatling.http.response" level="DEBUG" />-->

	<root level="INFO">
		<appender-ref ref="CONSOLE" />
	</root>

</configuration>
```

**Comment by h3xstream** [comment]
At the moment no, you need to disable the rule manually.
FindSecurityBugs does not have access to static files using SpotBugs API. In SpotBugs 3.0+, it might be different.
