### ISSUE TITLE
detect CWE-113 with sink  javax/servlet/http/HttpServletResponse.setHeader

### ISSUE THREAD

**Issue by bradflood** [find-sec-bugs/find-sec-bugs#354]
This issue is similar to #341.   It was found by IBM AppScan, which we are abandoning in favor of find-sec-bugs.  The code below is notional, as I have not verified it. If I have time this weekend, I can submit a PR for this and #341.
```java
package testcode.xss.servlets;

import org.apache.commons.lang.StringEscapeUtils;
import org.owasp.esapi.ESAPI;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

public class XssServlet7 extends HttpServlet {
	/*
 	 * source=java.io.FileInputStream.read(byte[]):int
	 * sink=javax.servlet.http.HttpServletResponse.setHeader(java.lang.String;java.lang.String):void
	 *
	 * possible solution: add to https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/main/resources/injection-sinks/xss-servlet.txt
	 * (needs verification): javax/servlet/http/HttpServletResponse.setHeader (ILjava/lang/String;ILjava/lang/String)V:0 
 	 */
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
    	File srcFile = new File("example.txt");
	FileInputStream fis = new FileInputStream(srcFile);
	
	byte b[] = new byte[1024];
	in.read(b);
	String zipFileName = "Example_Report_" + b + ".zip";
	response.setHeader("Content-Disposition", "attachment; filename=" + zipFileName);
	
    }
}
```

**Comment by h3xstream** [comment]
I left #341 open on purpose.. because it is really easy to implement and I was hoping for some hacktoberfest momentum to get new contributors.

Header splitting should be already covered : 
https://github.com/find-sec-bugs/find-sec-bugs/blob/89182fbefe3f45d38f874ef94b16c9862ba488d3/plugin/src/main/resources/injection-sinks/response-splitting.txt#L3-L7

**Comment by bradflood** [comment]
@h3xstream  I can take both 341 and 354.

**Comment by h3xstream** [comment]
@bradflood Cool 👍

**Comment by bradflood** [comment]
Verified comment from @h3xstream that this issue appears to be covered by existing response splitting checks.  

My client is using find-sec-bugs 1.6, sonar-findbugs 3.6, and it's possible this was fixed after 1.6.   I will verify at the client site using sonar-findbugs 3.7-SNAPSHOT 

I would like to keep this open until sonar-findbugs 3.7 is released.

**Comment by h3xstream** [comment]
If we look at the test cases, we already have, it should be covered.
https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/test/java/testcode/ResponseSplittingServlet.java#L17
https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/test/java/testcode/ResponseSplittingServlet.java#L32

The issue might not get reported if you only show normal and high priority. When FSB can't find the source, it will reported as low. Header injection is almost a vulnerability of the past, the likelyhood that your web server is vulnerable to header injection is low.
https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/main/java/com/h3xstream/findsecbugs/injection/crlf/CrlfLogInjectionDetector.java#L38-L55

**Comment by h3xstream** [comment]
I will open a new ticket to verify if `FileInputStream.read(X)` is tainting the parameter X.
https://github.com/find-sec-bugs/find-sec-bugs/search?l=Text&q=%22Stream.read%22

**Comment by h3xstream** [comment]
Ref #461
