### ISSUE TITLE
New Rule: Detect Information Exposure through printStackTrace()

### ISSUE THREAD

**Issue by HansolChoe** [find-sec-bugs/find-sec-bugs#356]
Hello.

Printing error messages to standard output may reveal security-sensitive information to users, and thus exposure of error messages would be vulnerable as reported by CWE-209 (https://cwe.mitre.org/data/deffinitions/209.html).

To detect possible exposures of error messages, I wrote a new detector that detects a method call to printStackTrace() as a bug, which possibly prints out sensitive system information to standard output. To reduce false alarms, I designed this detector focuses on the following 10 kinds of Exceptions which are also indicated by the CERT Oracle secure coding standard for Java:
* java.io.FileNotFoundException
* java.sql.SQLException
* java.net.BindException
* java.util.ConcurrentModificationException
* javax.naming.InsufficientResourcesException
* java.util.MissingResourceException
* java.util.jar.JarException
* java.security.acl.NotOwnerException
* java.lang.OutOfMemoryError
* java.lang.StackOverflowError

I implemented this detector, and now it is ready for the pull request. 
Please let me know if you like to send a pull-request for your review and merge. 

Thanks.

Hansol Choe

**Comment by h3xstream** [comment]
The detector was merged in #360
