### ISSUE TITLE
How to fix the xxe vuln when using Digester

### ISSUE THREAD

**Issue by JoyChou93** [find-sec-bugs/find-sec-bugs#362]
code:

```java
            String xml_con = request.getParameter("xml").toString();
            Digester digester = new Digester();
            digester.parse(new StringReader(xml_con));
```

How to fix the xxe vuln when using Digester? 
Thanks.

**Comment by JoyChou93** [comment]
solved.

```java
digester.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
```

**Comment by h3xstream** [comment]
I didn't know digester was a covered API for XXE.

What class is it exactly with the package name? And is it implementing SAXParser?

**Comment by JoyChou93** [comment]
@h3xstream It should be `XMLReader`

**Comment by h3xstream** [comment]
Thanks 
Ref: https://commons.apache.org/proper/commons-digester/commons-digester-3.0/apidocs/org/apache/commons/digester3/Digester.html
