### ISSUE TITLE
findbugs or findsecbugs problem when using maven

### ISSUE THREAD

**Issue by nimaj94** [find-sec-bugs/find-sec-bugs#368]
I am currently using findsecbugs and i use it using maven, so i put these lines in my pom in reporting plugins

```xml

<plugin>
<groupId>org.codehaus.mojo</groupId>
<artifactId>findbugs-maven-plugin</artifactId>
<version>3.0.5</version>
<configuration>
<plugins>
<plugin>
<groupId>com.h3xstream.findsecbugs</groupId>
<artifactId>findsecbugs-plugin</artifactId>
<version>LATEST</version>
<!-- Auto-update to the latest stable -->
</plugin>
</plugins>
</configuration>
</plugin>
```

but there is a problem.
when i execute site:site it create some directory inside my target folder.
 the directory is
C_\Users\ [myUserName] \ .m2\repository\com\h3xstream\findsecbugs\findsecbugs-plugin\1.7.1
 and findsecbugs-plugin-1.7.1.jar is inside this directory.
like it should be 
 C:\Users\ [myUserName] \ .m2\repository\com\h3xstream\findsecbugs\findsecbugs-plugin\1.7.1
but somebody accidentally use '_' instead of ':' .
you have to admit this looks really bad to put some jar file inside target folder, specially when it only contain plugin jar file and not other files and all of these still exist inside real m2 folder.

**Comment by h3xstream** [comment]
Do you have any special configuration for the **site** plugin?

Also, make sure you use the **latest spotbugs** rather than the **old findbugs** plugin:
https://github.com/find-sec-bugs/find-sec-bugs/wiki/Maven-configuration
Even you are not using the core rules, there are plenty of fixes.

**Comment by h3xstream** [comment]
The maven plugin repository will be the best place to report an issue if you still have a problem : https://github.com/spotbugs/spotbugs-maven-plugin/issues

Make sure you switch to spotbugs first.

**Comment by alambike** [comment]
FYI: Using LATEST to configure Spotbugs to use the LATEST version from findsecbugs plugin is deprecated:
https://github.com/spotbugs/spotbugs-maven-plugin/issues/144#issuecomment-532004142

And in fact it is no longer the recommended configuration for Maven in the findsecbugs wiki: https://github.com/find-sec-bugs/find-sec-bugs/wiki/Maven-configuration
