### ISSUE TITLE
Adding New Sinks

### ISSUE THREAD

**Issue by jyotigajrani** [find-sec-bugs/find-sec-bugs#378]
Hello,

Thanks for your quick responses earlier.
I am able to add custom sinks with command -

`java -Dfindsecbugs.injection.sources="/home/jyoti/replace.txt" -cp findbugs/\* edu.umd.cs.findbugs.LaunchAppropriateUI -low -pluginList plugins/findsecbugs-plugin-1.8.0.jar:plugins/noUpdateChecks.jar -include include.xml $@`

It is detecting vulnerability. Similarly I want to add custom sources for tainting Input. May you please tell the steps by which I can specify some Android API as source so that when ever the API is called, its parameters get tainted.  If I add API to any file in taint-config, it gives error while `mvn clean install`.

Thanks
Jyoti

**Comment by jyotigajrani** [comment]
Some mistake from my side. Done it.
Thanks

**Comment by h3xstream** [comment]
I was busy last week. I guess I can close this issue. If you can contribute the small mistake you made or the unclear steps, don't hesitate to document it in a comment.
