### ISSUE TITLE
Path traversal: Flase positive with static final variable

### ISSUE THREAD

**Issue by J0WI** [find-sec-bugs/find-sec-bugs#382]
I tried to work around #241 using a `static final` variable, but they're also considered as harmful:

```java
static final String FILE = "test.txt";
...
new File(FILE); //OK
```

`file` cannot be changed at all, so there is no path traversal vulnerability here.

**Comment by h3xstream** [comment]
@J0WI This case should already be covered.
I will investigate the case. Which compiler are you using (Java version) ?

**Comment by h3xstream** [comment]
I have pushed a new test that should cover the false positive you are describing #384

**Comment by J0WI** [comment]
I'm using
* openjdk version 1.8.0_162
* Gradle 4.7
* SpotBugs version 3.1.3
* Find Security Bugs 1.7.1

and can reproduce in a Docker build environment.

**Comment by J0WI** [comment]
@h3xstream it turns out that my test case was incomplete. I'm also using system properties (`System.getProperty("file.separator")`) in the static final variable which are treated as "user input".

**Comment by h3xstream** [comment]
@J0WI  I have created #385
