### ISSUE TITLE
Unable to resolve error in testcode sample

### ISSUE THREAD

**Issue by prashant4795** [find-sec-bugs/find-sec-bugs#383]
Hi

Me and my team is currently working on your tool findsecbugs for finding some more vulnerabilites in android.
In related to this we are facing some issues in writing the testcode samples. We are following all the steps as:

1:    Added entry in findbugs.xml for new bug
2:    Added entry in messages.xml
3:    Created new detector class and added code to it.
4:    Created test case...find-sec-bugs/plugin/src/test/java/android/
5:    Created vulnerable sample in find-sec-bugs/plugin/src/test/testcode/android

Here in testcode I'm writing a test case but it showing error in intent and startService() method which is perfectly working in android studio.

Also could you please tell us that how to integrate android library (android-support-v7-appcompat-master). And many classes like "android.content.Intent.class" in findsecbugs have less entries as compared to classes in sdk.

Attaching the screenshots of testcode and error generated.

Waiting anxiously for your reply 

Thank You 
Prashant Sharma

![screenshot from 2018-04-23 20-05-14](https://user-images.githubusercontent.com/25565875/39139882-ae660ede-4740-11e8-8e51-78435bdbb28a.png)

**Comment by h3xstream** [comment]
This is because the Intent class is only a stub: https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin-deps/src/main/java/android/content/Intent.java

Simply **create the constructor** that is missing. This is a bit time consuming when you are touching API that were not tested before.

**Comment by prashant4795** [comment]
Thanks for your reply
After creating the missing constructor, the errors are resolved after restarting and recompiling find-sec-bugs.

Prashant
