### ISSUE TITLE
False positive STRUTS_FORM_VALIDATION issues for ActionForms with proper validate method

### ISSUE THREAD

**Issue by dodie** [find-sec-bugs/find-sec-bugs#390]
The [StrutsValidatorFormDetector](https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/main/java/com/h3xstream/findsecbugs/StrutsValidatorFormDetector.java) creates a *Struts Form with no input validation* issue for every [ActionForm](https://svn.apache.org/repos/asf/struts/archive/trunk/struts-doc-1.1/api/org/apache/struts/action/ActionForm.html) class that does not extend [ValidatorForm](https://svn.apache.org/repos/asf/struts/archive/trunk/struts-doc-1.1/api/org/apache/struts/validator/ValidatorForm.html) or [DynaValidatorForm](https://svn.apache.org/repos/asf/struts/archive/trunk/struts-doc-1.1/api/org/apache/struts/validator/DynaValidatorForm.html).

It seems odd at first, because the `ActionForm` base class has a validate method that is capable of doing the validation. Based on the docs, I think the `ValidatorForm` and the `DynaValidatorForm` merely provide convenience to ease the validation process.

The [OWASP Struts page](https://www.owasp.org/index.php/Struts) suggest to use `ValidatorForm` or  `DynaValidatorForm` instead of  `ActionForm`, but the [first example](https://www.owasp.org/index.php/Struts_Validation_in_an_ActionForm) it provides simply use an `ActionForm` with a `validate` method.

The issue has a linked [CWE](http://cwe.mitre.org/data/definitions/106.html), but for me it does not shed much light on why I shouldn't use `ActionForm`, because the counter example it provides is an `ActionForm` *without* a `validate` method.

**Example code that raises an issue:**

```java
public class MyForm extends ActionForm {
  // ...
  public ActionErrors validate(ActionMapping mapping, HttpServletRequest request ) {
      // I validate my form, I promise!
  }
  // ...
}
```

**Suggestion:**
I think it would make sense to provide a configuration flag for this rule. Depending this config it could ignore if the `ActionForm` is not an actual subclass of `ValidatorForm` or `DynaValidatorForm`, but only check if it has the validate method.

I would happily prepare a PR if you think it's a good idea.

**Comment by h3xstream** [comment]
The idea of this detector is only to give a hint to developers or code auditors.

For developers, it is to suggest to add validation to reduce the potential attacks.
For the code auditor, it is informative to see that some endpoint might be easy targets because no validation is made.

Since it doesn't imply actual vulnerability, **this check could be lower to the priority LOW.** (By default, this will be hidden.)

**Comment by dodie** [comment]
Yes, I think it's best to think about this rule as a hint. However, in many cases it points out valid issues, but I think for many projects it creates too many false positves to be actually useful. 

(I think it's also not a good thing that it raises an issue for the [OWASP validation example](https://www.owasp.org/index.php/Struts_Validation_in_an_ActionForm).)

**Comment by h3xstream** [comment]
@dodie Does the method validate gets called when place in an ActionForm?

**Comment by dodie** [comment]
Cool, thanks!

**Comment by h3xstream** [comment]
- [x] ActionForm, ValidatorForm and DynaValidatorForm are treated equally (Low priority)
