### ISSUE TITLE
False Positive - JSTL Core accessing exported scoped variable storing the status of the iteration.

### ISSUE THREAD

**Issue by bradflood** [find-sec-bugs/find-sec-bugs#404]
The following results in an XSS_JSP_PRINT bugType being reported
```jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="core" %>
<!-- foo is considered safe --> 
<core:forEach items="${someList}" var="someForm" varStatus="foo">
			<tr title="row ${foo.index+1}">
</core:forEach>
```

However, the pageContext attribute named "foo" is not susceptible to manipulation. Per the spec, the name specified in varStatus is used to expose loop status. 

 It appears this is a second use case (along with https://github.com/find-sec-bugs/find-sec-bugs/issues/399) for marking the results of EL expression evaluation as safe when the expression only references objects under JSP container control.

I can submit a PR, but would like guidance as to how to implement.

**Comment by h3xstream** [comment]
Please include the disassembled bytecode associated with the JSP code.

**Comment by bradflood** [comment]
@h3xstream bytecode and configuration available at https://gist.github.com/bradflood/edb5b657a049460d6f1f5a385e5f304c

**Comment by h3xstream** [comment]
While I am looking for to white list expression such as `pageContext.request.contextPath`, I don't think we can easily handle `foo.index+1`.
It might look obvious that the property index is an integer but in fact, it could be a string property. 😬 
To analyze in depth these patterns a the JSTL would need to be parsed and passed to a symbolic execution mechanism. While SpotBugs already parsed and do advanced preprocessing on the bytecode. I don't much ROI for supporting cleanly JSTL.

My plan is to aim to support common expression that are standard and have low risk of being interpreted differently by JSTL implementations (I think they differ from one container to another).

**Comment by h3xstream** [comment]
A limited set of expression is now covered. See PR.
Expressions like  `foo.index+1` will continue to trigger FP.
