### ISSUE TITLE
Possible bug in DeserializationGadgetDetectorTest

### ISSUE THREAD

**Issue by mario-areias** [find-sec-bugs/find-sec-bugs#408]
It seems `DeserializationGadgetDetectorTest` is using a class that does not exist

https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/test/java/testcode/serial/commonscollections4/InvokerTransformer.java#L3

It looks to me that `Transformer` class lives on `org.apache.commons.collections4.Transformer` rather than `org.apache.commons.collections4.comparator.Transformer`. 

@h3xstream let me know if you agree with that or if I missed something. In case this is a bug I will send a PR in your way :smile:

**Comment by h3xstream** [comment]
Yes. You are right.
