### ISSUE TITLE
No class directories configured for FindBugs analysis error

### ISSUE THREAD

**Issue by georgThesis** [find-sec-bugs/find-sec-bugs#412]
I have a gradle multiproject build for scala. The regular `gradle findBugsMain` works great and also finds some security bugs. However the `findSecurityBugs` task fails with: `No class directories configured for FindBugs analysis error` . on

- windows
- centos
but compiles fine on anohter os like OsX

```
subprojects { subproject ->
    apply plugin: 'scala'
    apply plugin: 'findbugs'
    apply plugin: 'org.owasp.dependencycheck'

    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    dependencies {

        // security checks
        findbugs "com.google.code.findbugs:findbugs:$findBugsV"
        findbugs configurations.findbugsPlugins.dependencies
        findbugsPlugins "com.h3xstream.findsecbugs:findsecbugs-plugin:$findSecBugsV"
    }

    task findSecurityBugs(type: FindBugs) {

        classes = fileTree(project.rootDir.absolutePath).include("**/*.class");
        source = fileTree(project.rootDir.absolutePath).include("**/*.java");
        source = fileTree(project.rootDir.absolutePath).include("**/*.scala");
        classpath = files()
        pluginClasspath = project.configurations.findbugsPlugins

        findbugs {
            toolVersion = "$findBugsV"
            reportsDir = file("$project.buildDir/findbugsReports")
            //sourceSets = [sourceSets.main]
            effort = "max"
            reportLevel = "low"
            includeFilter = file("$rootProject.projectDir/fsb-include.xml")
        }
        tasks.withType(FindBugs) {
            reports {
                xml.enabled false
                html.enabled true
            }
        }

        dependencyCheck {
            analyzers {
                // disable .NET
                assemblyEnabled=false
            }
        }
    }
}

```

**Comment by h3xstream** [comment]
I have not used the latest and greatest gradle integration.

In theory, the latest version is the "spotbugs" plugin is not "findbugs".

Your config seems ok. The classes property is defined.. You can contact the developers of the Gradle integration here : https://github.com/spotbugs/spotbugs-gradle-plugin/issues

**Comment by timri** [comment]
Just in case anyone comes here via search (like myself): findBugs needs the classes to be present, but the gradle-task does not depend on any compile-tasks (at least with android that was the case).
I.e. calling "gradlew findSecurityBugs" resulted in the above error on a clean checkout of my project, but worked after "gradlew assembleDebug".
(In other words: it worked in my local copy, but failed in the CI-system ;-) )
