### ISSUE TITLE
Always prompt timeout when use version 1.8.0

### ISSUE THREAD

**Issue by dleyanlin** [find-sec-bugs/find-sec-bugs#424]
Always prompt timeout when use version 1.8.0 but success to analysis when use version 1.7.1

**Comment by h3xstream** [comment]
Missing detail: class files or code sample needed to reproduce.

**Comment by dleyanlin** [comment]
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.6:spotbugs (default-cli) on project XXXX: Execution default-cli of goal com.github.spotbugs:spotbugs-maven-plugin:3.1.6:spotbugs failed: Timeout: killed the sub-process -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
org.apache.tools.ant.ExitException: Permission ("java.lang.RuntimePermission" "exitVM") was not granted.
	at org.apache.tools.ant.types.Permissions$MySM.checkExit(Permissions.java:196)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:971)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:358)
Exception in thread "main" org.apache.tools.ant.ExitException: Permission ("java.lang.RuntimePermission" "exitVM") was not granted.
	at org.apache.tools.ant.types.Permissions$MySM.checkExit(Permissions.java:196)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:971)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:364)

**Comment by h3xstream** [comment]
You can try to increase the allowed time to scan the code.
https://spotbugs.github.io/spotbugs-maven-plugin/spotbugs-mojo.html#timeout

I suspected that the project has multi-millions lines of code. If this is not the case, the scanner is not working as expected.

**Comment by dleyanlin** [comment]
timeout to set <timeout>3600000</timeout>, but same code version 1.7.1 is work well

thanks

**Comment by h3xstream** [comment]
Closing this ticket. The timeout is arbitrary. It was an additional safeguard that the Maven plugin developer added. Keep in mind that with all the new addition there is always a small increase in code scan time. It is likely that the scan was already taking close to an hour in 1.7.1.

If you don't like the feature, it can be set to 9999999999999. (I have use this for project of multi-millions of lines of code.)
