### ISSUE TITLE
How can I create AntScript using FindSecurityBugs?

### ISSUE THREAD

**Issue by yprefer** [find-sec-bugs/find-sec-bugs#431]
This Is SpotBugs AntScript
----------------------------------------------------------
<taskdef resource="edu/umd/cs/findbugs/anttask/tasks.properties" classpath="path/to/spotbugs-ant.jar" />
<property name="spotbugs.home" value="/export/home/daveho/work/spotbugs" />

<target name="spotbugs" depends="jar">
  <spotbugs home="${spotbugs.home}"
            output="xml"
            outputFile="bcel-sb.xml" >
    <auxClasspath path="${basedir}/lib/Regex.jar" />
    <sourcePath path="${basedir}/src/java" />
    <class location="${basedir}/bin/bcel.jar" />
  </spotbugs>
</target> 
-----------------------------------------------------------

How Can I Plugin FindSecurityBugs in this???

**Comment by h3xstream** [comment]
@yprefer Please use the suggested channel : https://stackoverflow.com/questions/ask?tags=find-sec-bugs,spotbugs,java

Please refer to http://findbugs.sourceforge.net/manual/anttask.html in your question.
