### ISSUE TITLE
The following classes needed for analysis were missing for method names

### ISSUE THREAD

**Issue by dellgreen** [find-sec-bugs/find-sec-bugs#440]
## Environment

| Component          | Version |
| ------------------ | ------- |
| Maven              | n/a   |
| Gradle             | 5.0   |
| Java               | 1.8.0_191 (Oracle Corporation 25.191-b12)  |
| SpotBugs           | 3.1.8/3.1.9  |
| FindSecBugs        | 1.8.0   |
| Ant        |Apache Ant(TM) version 1.9.13 compiled on July 10 2018  |
| Groovy        |2.5.4 |
| Kotlin        |1.3.10|
| Kotlin DSL       |1.0.4|

## Problem

I am getting the following message when using findsecbugs spotbugs plugin in gradle. It is listing method names as missing classes, surely this cant be correct or am i missing something?

"The following classes needed for analysis were missing:
  getZone
  get
  test
  apply
  accept
  isAccessPoint
  isAwake
  run
  onTimeoutElapsed
  newThread
  onReply
  getId"

**Comment by h3xstream** [comment]
I think this is an artifact from something missing in the spotbugs Java 8 support.
https://github.com/spotbugs/spotbugs/issues/6

**Comment by h3xstream** [comment]
Issue is from SpotBugs

**Comment by ati90ati** [comment]
Added example project to reproduce:
https://github.com/ati90ati/bugreport-spotbugs-gradle-plugin-logging

https://github.com/spotbugs/spotbugs/issues/527

**Comment by clistoq** [comment]
Do you want to do something with this issue? I have the same issue on maven.
