### ISSUE TITLE
Which detectors support detecting groovy projects

### ISSUE THREAD

**Issue by HadesFX** [find-sec-bugs/find-sec-bugs#442]
i want to konw which detectors can work in detecting groovy projects and Is there an example to test? thank you very much.....

**Comment by h3xstream** [comment]
## Detectors (rules)
There are not much rules for Groovy specific API. However, any use of Java API will be analyzed. For this reason, it is better to keep all rules activated.

## Compilation
Groovy compile by default in a highly dynamic way. To support the analysis by spotbugs, you need to enable `CompileStatic` flag.
https://github.com/find-sec-bugs/find-sec-bugs-demos/tree/master/groovy-simple
