### ISSUE TITLE
Version mismatch in the findsecbugs-cli sh script.

### ISSUE THREAD

**Issue by marcan2020** [find-sec-bugs/find-sec-bugs#445]
## Environment

https://github.com/find-sec-bugs/find-sec-bugs/releases/download/version-1.8.0/findsecbugs-cli-1.8.0.zip

## Problem

Version mismatch in the findsecbugs-cli sh script. It should be 1.8.0 instead of 1.7.1.

**lib/findsecbugs-plugin-1.7.1.jar -> lib/findsecbugs-plugin-1.8.0.jar**

## Code

findsecbugs.sh
```
SOURCE="${BASH_SOURCE[0]}"
java -cp "$SOURCE/lib/\*:" edu.umd.cs.findbugs.LaunchAppropriateUI -quiet -pluginList lib/findsecbugs-plugin-1.7.1.jar -include include.xml $@
```

**Comment by h3xstream** [comment]
Should be fix by #447
