### ISSUE TITLE
This is not working with Intellij

### ISSUE THREAD

**Issue by Amerkashi** [find-sec-bugs/find-sec-bugs#455]
## Environment
Maven 3.6 / windows 10

## Problem
Your tutorial indicates that this should work with Intellij, but it can't find the security bug that I know for sure is security issue - hp fortify catches the issue

Do you have the find-sec-bug plugin for Intellij - not the findBugs

**Comment by karanb192** [comment]
After adding the find-bugs plugin, you need to add find-sec-bugs plugin to that. 
See the screenshot below -

![image](https://user-images.githubusercontent.com/3264937/53300187-b6bbe700-3869-11e9-8aaf-2b399098c504.png)

**Comment by h3xstream** [comment]
@Amerkashi Did it answer your question?

Note: that IDE plugins need to be update manually. https://find-sec-bugs.github.io/download.htm

**Comment by h3xstream** [comment]
Complete tutorial : https://github.com/find-sec-bugs/find-sec-bugs/wiki/IntelliJ-Tutorial
