### ISSUE TITLE
How to generate the machine under stable format?

### ISSUE THREAD

**Issue by mohammadreza-ashouri** [find-sec-bugs/find-sec-bugs#458]
How to generate the machine under stable format?
For instance, how can I extract such format? What does it call?

java/lang/Runtime.exec([Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/Process;:0,1

**Comment by h3xstream** [comment]
The sink file format is described here :
https://github.com/find-sec-bugs/find-sec-bugs/wiki/Injection-detection#sink-file-format

**Comment by mohammadreza-ashouri** [comment]
Thank you!

**Comment by mohammadreza-ashouri** [comment]
May I have the source code of signature-helper to contribute to my project?

**Comment by h3xstream** [comment]
It's just a javascript parser.
https://github.com/find-sec-bugs/signature-helper

You can copy-paste the skeleton of your class and it will generate the signatures.
