### ISSUE TITLE
1.8.0 findsecbugs.sh script errors

### ISSUE THREAD

**Issue by BuffaloWill** [find-sec-bugs/find-sec-bugs#460]
## Environment
FindSecBugs 1.8.0

| Component          | Version |
| ------------------ | ------- |
| FindSecBugs        | 1.8.0  |

## Problem
I wanted to test out findsecbugs CLI as discussed in https://github.com/find-sec-bugs/find-sec-bugs/wiki/CLI-Tutorial. I downloaded the 1.8.0 release and ran the code as described:

```
./findsecbugs.sh [JAR FILE]

./findsecbugs.sh: line 1: $'\r': command not found
./findsecbugs.sh: line 3: $'\r': command not found
Error: Could not find or load main class edu.umd.cs.findbugs.LaunchAppropriateUI
```
1. To fix the \r error (I think caused by saving the sh in Windows):
```
sed -i 's/\r$//' findsecbugs.sh
```
worked.

2. Changing line 4 from:
```
java -cp "$SOURCE/lib/\*:" edu.umd.cs.findbugs.LaunchAppropriateUI -quiet -pluginList lib/findsecbugs-plugin-1.7.1.jar -include include.xml $@
```
to
```
java -cp lib/*: edu.umd.cs.findbugs.LaunchAppropriateUI -quiet -pluginList lib/findsecbugs-plugin-1.7.1.jar -include include.xml $@
```
fixed the path issue. Not sure the proper way this script should be deployed so I took my best guess and put it in the root find-sec-bugs dir. Running from the root dir takes away the need for `$SOURCE` AFAIK. I think `\*` will always cause issues. 

- ubuntu 18.04
- bash 4.4.19

Thank you!

**Comment by h3xstream** [comment]
You can replace the .sh by this one --> https://github.com/find-sec-bugs/find-sec-bugs/blob/master/cli/findsecbugs.sh

Side note : I am going to do a release this week that will include this fix.

**Comment by BuffaloWill** [comment]
Ah cool. Thanks!!
