### ISSUE TITLE
PATH_TRAVERSAL_IN  detection

### ISSUE THREAD

**Issue by witchnya** [find-sec-bugs/find-sec-bugs#470]
## Environment

| Component          | Version |
| ------------------ | ------- |
| Maven              | 3.5.3  |
| Java               | 1.8.0_181  |
| SpotBugs           | 3.1.11  |
| FindSecBugs        | 1.9.0  |

## Problem

I think It is too strict this detection.
I use only "public static final String" type for parent directory string argument,
but find-sec-bugs indicates as a PATH_TRAVERSAL_IN bug. 

## Code (If needed)

```java

String DIR1 = ".";
File t1 = new File(DIR1, FilenameUtils.getName(configFileName)); // BUG NOT Detected
LOG.debug(t1.toString());
		
String DIR2 = "." + File.separator;
File t2 = new File(DIR2, FilenameUtils.getName(configFileName)); // BUG Detected
LOG.debug(t2.toString()); 

```

**Comment by h3xstream** [comment]
It would make sense to add all four static fields : https://docs.oracle.com/javase/7/docs/api/java/io/File.html#field_summary

Also `FileSystem.getSeparator()` should be supported
https://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystem.html#getSeparator()
