### ISSUE TITLE
Detect if authorisation is missing from a RequestMapping 

### ISSUE THREAD

**Issue by karanb192** [find-sec-bugs/find-sec-bugs#473]
Developers often tend to miss authorisation for some APIs which leads to a critical security issue. I would like add a warning if they are missing authorisation check for any of the APIs.

**Comment by h3xstream** [comment]
What would be the heuristic for detecting that a feature required authentication ?

Please provide some code samples.

**Comment by h3xstream** [comment]
Missing information
