### ISSUE TITLE
SpringEntityLeakDetector throw s NPE

### ISSUE THREAD

**Issue by bananayong** [find-sec-bugs/find-sec-bugs#477]
## Environment

| Component          | Version |
| ------------------ | ------- |
| Maven              | 3.6.0   |
| Java               | jdk-11.0.2  |
| SpotBugs           | 3.1.12   |
| FindSecBugs        | 1.9.0   |

## Problem
I got some problem when run spotbugs with find-sec-bugs plugin.
The issue is that SpringEntityLeakDetector throws NPE when some interface has `@RequestMapping` annotations.
For feign client I need to put spring MVC annotations on interface.

I think that problem is from `MethodGenFactory#analyze`.
That method returns null when `method.getCode() == null`.
So, (`MethodGen methodGen = classContext.getMethodGen(m);`) methodGen can be null.
NPE is thrown on `List<String> classesToInspect = new ArrayList<>(Arrays.asList(methodGen.getReturnType().toString()));`

It looks like to solve the issue by skipping when methodGen is null.

Is there any workaround for this problem?
Let me know please.

Thank you!

## Code (If needed)

```java
// FeignClient
public interface RemoteClient {
    @RequestMapping(path = "/hello/{name}", method = RequestMethod.GET)
    Hello hello(@PathVariable String name);
}
```

I made sample project to reproduce this issue.
https://github.com/bananayong/spring-entity-leak-detector-issue

**Comment by reitzmichnicht** [comment]
I have the same issue, but other usecase. We use the annotated interfaces to separate it from the controller code, so the controller implements the interface with the annotated methods.
