### ISSUE TITLE
http://find-sec-bugs.github.io/bugs.htm#SQL_INJECTION_HIBERNATE

### ISSUE THREAD

**Issue by danijelst** [find-sec-bugs/find-sec-bugs#482]
According to the documentation of [SQL_INJECTION_HIBERNATE](http://find-sec-bugs.github.io/bugs.htm#SQL_INJECTION_HIBERNATE) the [CWE-89](http://cwe.mitre.org/data/definitions/89.html) is covered with this. But the [CWE-564](http://cwe.mitre.org/data/definitions/564.html) is not mentioned in the documentation. But how I understand it, the [CWE-564](http://cwe.mitre.org/data/definitions/564.html) is covered as well and therefore the documentation should be extended in my point of view

**Comment by h3xstream** [comment]
Yes we can definitely add this CWE reference in the description.

I will keep the generic cwe (SQL injection) in the metadata of the rules. The rule is more than 5 years old. The detector detects both HQL and SQL injection in Hibernate API.

https://github.com/find-sec-bugs/find-sec-bugs/blob/5ac905c9b49492a10692bd7fe12b7a21baf15938/findsecbugs-plugin/src/main/resources/metadata/findbugs.xml#L190-L192
