### ISSUE TITLE
Scans Binaries not source code

### ISSUE THREAD

**Issue by salecharohit** [find-sec-bugs/find-sec-bugs#484]
## Environment

Java 8/ FindSecBugs 1.8.0 CLI

| Component          | Version |
| ------------------ | ------- |
| FindSecBugs-CLI| 1.8.0   |

## Problem

I am using findsecbugs-cli to scan our code a java web application. I have realised is that this tool is scanning only binaries i.e. .jar and .war files only usually in the target folder. If there are no binaries in the source folder then it says artifacts not found. This is kind of problematic because in our pipeline we intend to first scan our code and then build it. However now we have to first build our code , generate the war file and then feed it to find-sec-bugs scanner. 
Want to know is this the default behaviour as planned ? Or am i doing something wrong and that there is a way we can directly scan the code ?

**Comment by h3xstream** [comment]
The cli is intended to receive **a single jar or a list of jar**. WAR is a not a JAR. [[Ref]](https://github.com/find-sec-bugs/find-sec-bugs/wiki/CLI-Tutorial)

If you are building your project from your source with either Maven or Gradle, you should probably use the respective plugin unless you want to scan dependencies.
