### ISSUE TITLE
Support for kotlin scanning

### ISSUE THREAD

**Issue by bharat-srinivasan** [find-sec-bugs/find-sec-bugs#486]
I am trying to use Spotbugs with find-sec-bugs enabled on my Kotlin project. I wanted to know if it is advised to use this plugin for Kotlin security scan?

**Comment by h3xstream** [comment]
I'm putting some effort in the support for Kotlin.
Kotlin compiler is producing very clean bytecode. The bytecode is very close to Java. Its support makes perfect senses.

We have identified minor issue ([which were fixed](https://github.com/find-sec-bugs/find-sec-bugs/issues?q=is%3Aissue+kotlin+is%3Aclosed)). Find Security Bugs is Kotlin ready. However, the different integration for SpotBugs IDE / CI do not support Kotlin in most case.
I don't have plugin to recommend at the moment.
