### ISSUE TITLE
https://find-sec-bugs.github.io/bugs.htm#SQL_INJECTION_SPRING_JDBC detects method from "solution"

### ISSUE THREAD

**Issue by inekrashevych-callfire** [find-sec-bugs/find-sec-bugs#487]
## Environment

sonar with find-sec-bugs rules enabled, java 1.8, spring 5.0.10.RELEASE

## Problem

The method that is described as a solution from bug description is also detected as a bug, since the method is listed in the injection links:
https://github.com/find-sec-bugs/find-sec-bugs/blob/2340b90bc3993a595011e1cce20982533799cc0d/findsecbugs-plugin/src/main/resources/injection-sinks/sql-spring.txt#L113

So, I think either description has to be fixed to say that jdbcTemplate shouldn't be used at all, or methods with parameters whitelisted back.

**Comment by h3xstream** [comment]
For the following code, their will be no vulnerability. The first parameter which contains the query is indeed injectable. However, the dynamic values place as varargs (argument 3, 4, 5, ... ) will be escaped properly when place in the query. 
```java
JdbcTemplate jdbc = new JdbcTemplate();
int count = jdbc.queryForObject("select count(*) from Users where name = ?", Integer.class, paramName)
```
