### ISSUE TITLE
Spring Entity Leak Detector for collections

### ISSUE THREAD

**Issue by karanb192** [find-sec-bugs/find-sec-bugs#495]
Hi @h3xstream,

I would like to extend this detector to catch cases when collection of entities are being returned or taken as argument in Controller methods. What do you think?

I'm already working on it but facing some issues.

**Comment by h3xstream** [comment]
It was implemented here : #496

**Comment by h3xstream** [comment]
You take a look at all the cases supported : https://github.com/find-sec-bugs/find-sec-bugs/blob/master/findsecbugs-samples-java/src/test/java/testcode/spring/SpringEntityLeakController.java

**Comment by karanb192** [comment]
It's alright.
Thanks for adding the feature.
