### ISSUE TITLE
SQL Injection false positive with MessageFormat.format()

### ISSUE THREAD

**Issue by danielfn** [find-sec-bugs/find-sec-bugs#498]
## Environment

| Component          | Version |
| ------------------ | ------- |
| Maven              | `3.5.4`   |
| Gradle             | `-`   |
| Java               |  `1.8.0_222`  |
| SpotBugs           | `3.1.12`   |
| FindSecBugs        | `1.9.0` and `1.10.0-SNAPSHOT` (built from master @ c1f895ca2 ) |

## Problem

We are getting a `SQL_INJECTION_SPRING_JDBC` error when building a SQL query with `MessageFormat.format()`, even though all the parameters passed are static final strings.
 
## Code

```java
import java.text.MessageFormat;
import org.springframework.jdbc.core.JdbcTemplate;

public class SqlJdbcSpring {

  private JdbcTemplate template = new JdbcTemplate();
  private static final String tableName = "mytable";
  private static final String idName = "myid";

  public void testInjectionMessageFormat(final Long id) {
    // findsecbugs KO
    final String sql = MessageFormat.format("DELETE {0} WHERE {1}=?", tableName, idName);
    this.template.update(sql, id);
  }

  public void testInjectionStringConcat(final Long id) {
    // findsecbugs OK
    final String sql = "DELETE " + tableName + " WHERE " + idName + "=?";
    this.template.update(sql, id);
  }
}
```

**Comment by h3xstream** [comment]
Case similar to the one you provided will not be reported. However if the value pass to the format method are not constant value a potential injection will be reported. (see second code sample)

# False Positive

https://github.com/h3xstream/find-sec-bugs/blob/d31f42310bf5e53366e4299400b77057e6a99de5/findsecbugs-samples-java/src/test/java/testcode/sqli/msgformat/SpringJdbcWithMessageFormatFP.java#L11-L25


# Potential injection

https://github.com/h3xstream/find-sec-bugs/blob/d31f42310bf5e53366e4299400b77057e6a99de5/findsecbugs-samples-java/src/test/java/testcode/sqli/msgformat/SpringJdbcWithMessageFormatVulnerable.java#L9-L16

**Comment by danielfn** [comment]
I just built a new snapshot from master and I can confirm that the issue is gone. Thank you @h3xstream :)
