### ISSUE TITLE
How can I use FindBugs without IDE?

### ISSUE THREAD

**Issue by wjcIvan** [find-sec-bugs/find-sec-bugs#503]
How can I use FindBugs without IDE? Such as use a jar and scan the source code.

**Comment by skirge** [comment]
This is how I use it:
```
SRCDIR=$1

usage() {
	echo "Usage: $0 <srcdir>"
	exit 1
}

if [ -z $SRCDIR ]; then
	usage
fi

SOURCEPATH="$(find $SRCDIR -name java -exec echo -sourcepath '{}' \; | xargs)" 

echo spotbugs -maxHeap 8192 -textui -workHard -xml:withMessages -progress -quiet -bugCategories SECURITY -effort:max -experimental -exclude ~/cfg/fb/exclude.xml -output fbfull.xml -projectName EPAY -nested:true $SOURCEPATH $SRCDIR

spotbugs -maxHeap 8192 -textui -workHard -xml:withMessages -progress -quiet -bugCategories SECURITY -effort:max -experimental -exclude ~/cfg/fb/exclude.xml -output fbfull.xml -projectName FBFULL -nested:true $SOURCEPATH $SRCDIR
```

This scans project (compiled sources) and project libraries (`-nested:true`). Output file can be then opened by Spotbugs GUI or in IntelliJ IDEA Findbugs plugin.

**Comment by h3xstream** [comment]
Just for the record, every release has a zip archive of the command line version. A start script is present for both Windows and Linux.
https://github.com/find-sec-bugs/find-sec-bugs/releases
