### ISSUE TITLE
Support com/google/common/escape/Escaper as sanitizer

### ISSUE THREAD

**Issue by h3xstream** [find-sec-bugs/find-sec-bugs#504]
## Description

com/google/common/escape/Escaper.escape() is often used to encode URL parameter.

While the interface is generic and could be implemented by any type of escaping, it is highly likely to be for URL. https://guava.dev/releases/19.0/api/docs/com/google/common/net/UrlEscapers.html

## Code

Test case provided by @	RichardBradley

Bad : 
```java
import javax.ws.rs.core.Response;
import org.apache.http.client.methods.HttpGet;

public Response get(String x, String y) throws IOException {

    String url = String.format("%s/%s",
            x,
            y);

    HttpGet request = new HttpGet(url); // HERE

    ...
}
```

Good:
```java
import javax.ws.rs.core.Response;
import org.apache.http.client.methods.HttpGet;
import static com.google.common.net.UrlEscapers.urlPathSegmentEscaper;

public Response get(String x, String y) throws IOException {

    String url = String.format("%s/%s",
            urlPathSegmentEscaper().escape(x),
            urlPathSegmentEscaper().escape(y));

    HttpGet request = new HttpGet(url);

    ...
}
```

**Comment by h3xstream** [comment]
Open to close #346

**Comment by h3xstream** [comment]
For somebody to do this "quick" win:
`com/google/common/escape/Escaper.escape()`. Here is an example of configuration for URLEncoder.
https://github.com/find-sec-bugs/find-sec-bugs/blob/a1a27aca43a0a4cc6ee680b3b978fa2916288f00/plugin/src/main/resources/safe-encoders/other.txt#L1-L4

**Comment by thiyagu-7** [comment]
I would like to take this for this hacktoberfest

**Comment by h3xstream** [comment]
@thiyagu-7 Perfect! I have assigned you to this issue.
