### ISSUE TITLE
findsecbugs.sh has windows line breaks

### ISSUE THREAD

**Issue by MarcSchoenefeld** [find-sec-bugs/find-sec-bugs#516]
## Environment

| Component          | Version |
| ------------------ | ------- |
| FindSecBugs CLI       |1.9.0-fix1   |

## Problem

The start up script findsecbugs.sh has windows line endings, which causes failure when executing on macOS (tested), and likely on Linux. 

Please consider testing the cli distribution on non-windows machines, too (RFE?) .

**Comment by MarcSchoenefeld** [comment]
The workaround I used until fixed:

awk 1 RS='\r\n' ORS= <findsecbugs.sh >fsb.sh

**Comment by h3xstream** [comment]
I've repackage the cli. https://github.com/find-sec-bugs/find-sec-bugs/releases/tag/version-1.9.0

I did a simple "dos2unix findsecbugs.sh"

Not sure what was the source for this `\r` character.

**Comment by kiwiz** [comment]
Looks like this is an issue on the 1.11.0 release:
```
$ ./findsecbugs.sh
-bash: ./findsecbugs.sh: /bin/bash^M: bad interpreter: No such file or directory
```
