### ISSUE TITLE
cli to scan SOURCE CODE

### ISSUE THREAD

**Issue by drwetter** [find-sec-bugs/find-sec-bugs#523]
Hi,

thanks for the cool project!

For pentesting I often get sources which do not compile as libraries e.g. are missing. So using a IDE plugin is not an option (see also #484). Besides, I can better automate things on the command line.

I either get a WAR (then, depending on the code, ~90% of the complaints a within the external libraries), or just sources, or sources with maybe some pom.xml and external libraries missing.

Thx, Dirk

**Comment by h3xstream** [comment]
You should be able to scan package WAR. Compiled classes are usually located in `./WEB-INF/classes/`. 

JSP -which may contain XSS- are often not compiled. This require some manual work. Here is a sample project that serve as a template to compiled JSP: https://github.com/find-sec-bugs/find-sec-bugs-demos/tree/master/java-web-jsp

**Comment by drwetter** [comment]
Thanks, will look at the demo.

1) Scanning a WAR (if available) is an option. However, see #524. And sometimes the compiled classes are someplace else. I have a WAR file now where there are mostly in ./WEB-INF/lib/ :-(

Still, it would be great if I could scan the source code if available.
