### ISSUE TITLE
custom report files

### ISSUE THREAD

**Issue by xsser** [find-sec-bugs/find-sec-bugs#534]
Q1:
How i generate my own report in chinese? 
Q2:
Is there any custom way to modify my report files?

**Comment by h3xstream** [comment]
Q1:
Please provide the tool integration you are using.

Q2:
SpotBugs HTML can be customized with a XSLT stylesheet.
https://spotbugs.readthedocs.io/en/stable/running.html

**Comment by xsser** [comment]
thanks in advance
