### ISSUE TITLE
False positive spring jdbctemplate SQL Injection

### ISSUE THREAD

**Issue by dcherix** [find-sec-bugs/find-sec-bugs#538]
## Environment

| Component          | Version |
| ------------------ | ------- |
| Maven              | ?????   |
| Gradle             | 6.0.1   |
| Java               | 8   |
| SpotBugs           | 3.1.12  |
| FindSecBugs        | 1.8.0   |

## Problem

[Find Security Bugs | Security | SQL_INJECTION_SPRING_JDBC] when using PreparedStatementSetter our BatchPreparedStatementSetter. Due to the use of PreparedStatement it's a false positive error.

## Code

```java
public class BugSample1 {
 private JdbcTemplate jdbcTemplate;
  
  public void someSqlCode(Object o){
     this.jdbcTemplate.update(substitutor.replace(DELETE_PERMISSION), ps -> {
            ps.setString(1, o.getType());
            ps.setLong(2, o.getIdentifier());
        });
}
}
```

**Comment by h3xstream** [comment]
Is the value DELETE_PERMISSION a constant string (final static) ?

**Comment by dcherix** [comment]
Yes it is

**Comment by yahanvesh** [comment]
Any update on this?

**Comment by h3xstream** [comment]
Not yet evaluate in depth .. mark so that I don't forget about it.

**Comment by h3xstream** [comment]
Both classes are now supported.
