### ISSUE TITLE
how to debug find-sec-bug-cli

### ISSUE THREAD

**Issue by m4p1e** [find-sec-bugs/find-sec-bugs#542]
is there a way to debug for printf taint process?  like a option for finsecbugs.sh?

**Comment by m4p1e** [comment]
i tried
```
findsecbugs_taint_debugtaintstate=true ./findsecbugs.sh
```
but its not work

**Comment by m4p1e** [comment]
1. step  set config

```java
///root/find-sec-bugs/findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/FindSecBugsGlobalConfig.java 
 private boolean debugPrintInstructionVisited = true;
 private boolean debugPrintInvocationVisited = true;
```
2. add debug print
```diff
    public void analyzeInstruction(Instruction ins) throws DataflowAnalysisException {
        //Print the bytecode instruction if it is globally configured
        if (FindSecBugsGlobalConfig.getInstance().isDebugPrintInvocationVisited()
                && ins instanceof InvokeInstruction) {
+            System.out.println(getFrame().toString());
            ByteCode.printOpCode(ins, cpg);
        } else if (FindSecBugsGlobalConfig.getInstance().isDebugPrintInstructionVisited()) {
+          System.out.println(getFrame().toString());
            ByteCode.printOpCode(ins, cpg);
        }
        super.analyzeInstruction(ins);
    }
```
3. step recompile project and make package 
4. step replace ./cli/lib/findsecbugs-plugin-verison.jar  to the new one

**Comment by h3xstream** [comment]
These options are used when running unit test. TDD is the preferred approach for developing new bug pattern detector.

You will see that it is commented as it is used temporarily:
https://github.com/find-sec-bugs/find-sec-bugs/blob/2340b90bc3993a595011e1cce20982533799cc0d/findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/PotentialValueDetectorTest.java#L34-L37

The easiest option is to create a simple test case.
