### ISSUE TITLE
How to extract the sourceInfo from sourcecode?

### ISSUE THREAD

**Issue by Lz1y** [find-sec-bugs/find-sec-bugs#547]
I noticed there is a parameter called `-sourceInfo`, but how do i use this feature. 
`Line numbers` in scan report deviates from the other decompiler like idea's decompiler.
How to extract the sourceInfo from sourcecode to fix offsets?

**Comment by h3xstream** [comment]
I am not fully aware of how `-sourceInfo` parameter is working but here is what I know..

By default Spotbugs will report line number based on the information provided in classes files. This is only available if the code was compiled with debug information. (Usually the default for most build system.) The location of fields and code segments other than methods are not included by the Java compiler.
SpotBugs give you the option to define custom mapping to map findings to more precise line of code. This is useful if you have lots of findings associated to fields. It is also be a good option for JVM languages.

You can find a description of the format here:
https://github.com/spotbugs/spotbugs/blob/3883a7b750fb339577be073bc45e36b6f268777b/spotbugs/src/doc/sourceInfo.html

**Comment by Lz1y** [comment]
Your answer is very useful, thanks for your reply!
