### ISSUE TITLE
Maintain different versions of the page: https://find-sec-bugs.github.io/bugs.htm

### ISSUE THREAD

**Issue by saikat056** [find-sec-bugs/find-sec-bugs#548]
# Environment
FindSecBugs: 1.10.1

# Problem
The bugs pattern page(https://find-sec-bugs.github.io/bugs.htm) does not contain any section for 
SQL_NONCONSTANT_STRING_PASSED_TO_EXECUTE. In the old version of FindSecBugs, we were able to go to 
https://find-sec-bugs.github.io/bugs.htm#SQL_NONCONSTANT_STRING_PASSED_TO_EXECUTE

This provides inconsistent URL information about vulnerability in the report generated by old version of FindSecBugs.

# Solution
It would be great if we can provide versioning of bugs pattern page. Then, we can refer to the page depending on the version of FindSecBugs.

**Comment by h3xstream** [comment]
SQL_NONCONSTANT_STRING_PASSED_TO_EXECUTE is associated to a bug pattern that is part of SpotBugs core rules.

https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html#sql-nonconstant-string-passed-to-execute-or-addbatch-method-on-an-sql-statement-sql-nonconstant-string-passed-to-execute

**Comment by h3xstream** [comment]
In early version, the SQL INJECTION bug patterns was divide in JDBC, Hibernate, JDO and JPA in order to have specialized descriptions.
Other than that, we are only adding Bug pattern description so far.
