### ISSUE TITLE
Hello,will you continue developing the FindBugs plugin?

### ISSUE THREAD

**Issue by 839588378** [find-sec-bugs/find-sec-bugs#550]
I am now using the latest version of idea(2020.1), which cannot be compatible with the plug-in. This plug-in is too good to use to give up

**Comment by h3xstream** [comment]
I did an attempt to ported it last year.. Unfortunately, I don't have the time.

**Comment by h3xstream** [comment]
The SpotBugs plugin for IntelliJ is now the standard option. You should be able to find it on the Plugins Marketplace.
https://plugins.jetbrains.com/plugin/14014-spotbugs
https://github.com/JetBrains/spotbugs-intellij-plugin
