### ISSUE TITLE
How to remove “taint” for custom tld function?

### ISSUE THREAD

**Issue by slmint** [find-sec-bugs/find-sec-bugs#555]
fork: [swa-function](https://github.com/slmint/find-sec-bugs)

```jsp
<%@taglib prefix="swa" uri="self-web-analysis" %>
<%@taglib prefix="e" uri="https://www.owasp.org/index.php/OWASP_Java_Encoder_Project" %>

${unknown}

${swa:htmlEscape(unknown)}

${e:forHtmlContent(unknown)}
```
with findsecbugs.taint.customconfigfile
`
net/swa/util/SwaTldFunction.htmlEscape(Ljava/lang/String;)Ljava/lang/String;:0|+XSS_SAFE
`

line "swa" got "Potential XSS in JSP"

did i miss something or take a worng way?

**Comment by h3xstream** [comment]
At the moment expression are whitelist. We would have to add `swa:htmlEscape()`.

We are using Regex which cover most JSP cases. The reason are evaluated with regex is that string with `${...}` are converted to `PageContextImpl.evaluateExpression()` when JSP is compiled.

https://github.com/find-sec-bugs/find-sec-bugs/blob/master/findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/extra/JstlExpressionWhiteLister.java#L52

**Comment by slmint** [comment]
thanks

**Comment by h3xstream** [comment]
I thought swa was a library that was public 
I can't find any occurence of it ..https://www.google.com/search?q=%22swa%3AhtmlEscape%22
And I don't feel like guessing behavior base on function name (name is htmlEscape == safe). Custom function are more likely to have implementation errors.
