### ISSUE TITLE
src/test/java/testcode/serial/ObjectDeserializationFalsePositive2.java:[10,8] error: no suitable constructor found for ASN1InputStream(no arguments)

### ISSUE THREAD

**Issue by hktalent** [find-sec-bugs/find-sec-bugs#557]
mvn clean  package -DskipTests
[ERROR]
https://github.com/find-sec-bugs/find-sec-bugs/blob/98d62e120d716c76135d2a2f737cf5ac25101445/findsecbugs-samples-java/src/test/java/testcode/serial/ObjectDeserializationFalsePositive2.java#L7
src/test/java/testcode/serial/ObjectDeserializationFalsePositive2.java:[10,8] error: no suitable constructor found for ASN1InputStream(no arguments)
[INFO] Find Security Bugs Samples Java .................... FAILURE [  2.170 s]

**Comment by h3xstream** [comment]
`mvn clean install` should fix it temporarily. As it's using this stub version: https://github.com/find-sec-bugs/find-sec-bugs/blob/98d62e120d716c76135d2a2f737cf5ac25101445/findsecbugs-samples-java/src/test/java/testcode/serial/ObjectDeserializationFalsePositive2.java#L7.

It would make sense to fix it by using one of the real constructors.
http://people.eecs.berkeley.edu/~jonah/bc/org/bouncycastle/asn1/ASN1InputStream.html#ASN1InputStream(java.io.InputStream)
