### ISSUE TITLE
Weak Algorithm Name as String Parameter not detected after Transformation

### ISSUE THREAD

**Issue by LordAmit** [find-sec-bugs/find-sec-bugs#559]
## Environment

| Component          | Version |
| ------------------ | ------- |
| Java               |  OpenJDK version 1.8.0_232 64 bit  |
| SpotBugs           | 4.0.0   |
| FindSecBugs        | 1.10.1  |

## Problem

Weak algorithm names are not detected when they go through various types of transformations. We noticed this for both MessageDigest and Cipher unless otherwise specified.

## Code 

Replacing a Secure Parameter with an Insecure Parameter, e.g.: 

```java
MessageDigest.getInstance(“SHA-256”.replace(“SHA-256”, “MD5”));
```

Replacing an Insecure Parameter with an Insecure Parameter:

```java
Cipher.getInstance(“AES”.replace(“A”, “D”));
```

Transforming string case e.g., from lower to upper case:
_We noticed this only for MessageDigest, i.e. similar use for Cipher.getInstance was detected._

```java
MessageDigest.getInstance("md5".toUpperCase(Locale.ENGLISH));
```

Replacing a noisy version of insecure parameters:

```java
Cipher.getInstance(“DE$S”.replace(“$”, “”));
```

Inserting an Insecure Parameter via chaining method calls:

```java
public class CipherExample {
    private String cipherName = "AES/GCM/NoPadding";

    public CipherExample methodA() {
        cipherName = "AES/GCM/NoPadding";
        return this;
    }

    public CipherExample methodB() {
        cipherName = "DES";
        return this;
    }

    public String getCipherName(){
        return cipherName;
    }

    public static void main(String[] args) throws NoSuchAlgorithmException, NoSuchPaddingException {
        Cipher c = Cipher.getInstance(new CipherExample().methodA().methodB().getCipherName());

        System.out.println(c.getAlgorithm());
    }
}

```

where obj.A().getCipherName() returns the secure value,but 
obj.A().B().getCipherName(), and obj.B().getCipherName() return the
insecure value.

Please let me know if you need any additional information (e.g., logs from our side) in fixing these issues. 

Thank you for creating this awesome plugin :) 

\* My team is conducting academic research on Java Cryptography API based misuse using your tool.

**Comment by h3xstream** [comment]
This is not something that I'm interested to invest time for now.

We are implementing heuristic to detect true positive and to eliminate false positive,,, But in both case we are scoping to code that are written by human or a legitimate developper.

Their are tons of way to obfuscate the code flow: reflection, encapsulation, polluting code flow (with branch, useless instruction).
