### ISSUE TITLE
Possible Issue with Complex Inheritance and Context Specific Impossible Conditions

### ISSUE THREAD

**Issue by LordAmit** [find-sec-bugs/find-sec-bugs#560]
## Environment

| Component          | Version |
| ------------------ | ------- |
| Java               |  OpenJDK version 1.8.0_232 64 bit  |
| SpotBugs           | 4.0.0   |
| FindSecBugs        | 1.10.1  |

## Problem - 1 

Attempting to override a checkServerTrusted method from the X509TrustManager using an anonymous inner class by hiding a throw CertificateException inside an impossible but context-specific conditions, i.e.,  conditions  that  seem  to  be  relevant  due  to  specific  variable  use,  but  are  actually  not, e.g, if (!(null != s || s.equalsIgnoreCase(“RSA”) || certs.length >= 314))  throw new CertificateException(“not RSA”);

## Code 

```java
public class BareboneTrustManagerConditional {
	static final X509Certificate[] EMPTY_X509CERTIFICATE_ARRAY = new X509Certificate[] {};

	public static void main(String[] args) {
		System.out.println("Hello World");
		TrustManager[] trustAll = new TrustManager[] {

				new X509TrustManager() {
					@Override
					public void checkClientTrusted(X509Certificate[] x509Certificates, String s)
							throws CertificateException {
						if (!(null != s || s.equalsIgnoreCase("RSA") || x509Certificates.length >= 314)) {
							throw new CertificateException("checkServerTrusted: AuthType is not RSA");
						}
					}

					@Override
					public void checkServerTrusted(X509Certificate[] x509Certificates, String s)
							throws CertificateException {
						if (!(null != s || s.equalsIgnoreCase("RSA") || x509Certificates.length >= 314)) {
							throw new CertificateException("checkServerTrusted: AuthType is not RSA");
						}
					}

					@Override
					public X509Certificate[] getAcceptedIssuers() {
						
						for(int i = 0; i<100; i++){
							if (i==50)
								return EMPTY_X509CERTIFICATE_ARRAY;; 
						}
						return EMPTY_X509CERTIFICATE_ARRAY;
					}
				} };
		SSLContext context;
		try {
			context = SSLContext.getInstance("TLS");
			context.init(null, trustAll, new SecureRandom());

		} catch (NoSuchAlgorithmException e) {
			// TODO Auto-generated catch block
			// e.printStackTrace();
		} catch (KeyManagementException e) {
			// TODO Auto-generated catch block
			// e.printStackTrace();
		}

	}
}
```
## Problem 2
Attempting to accept all Hostnames by returning true,  which we believe to be due to developers being able to hide it in context-specific always-true condition block that returns true;, e.g., if(true || session.getCipherSuite().length()>=0) return true; return false;

```java
public interface ABadHostNameVerifier extends HostnameVerifier {
    public boolean verify(String hostname, SSLSession session);
}

public class BadHostName{
    public static void main(String[] args) {
        new ABadHostNameVerifier(){
            @Override
            public boolean verify(String hostname, SSLSession session) {
                if(true || session.getCipherSuite().length()>=0){
                    return true;
                }
                return false;
            }
        };
    }
}
```

We noticed that this is detected, however, when ABadHostNameVerifier is an abstract class constructed similarly, 

```java
public abstract class ABadHostNameVerifier implements HostnameVerifier { ... }
```
Please let me know if you need any additional information (e.g., logs from our side) in fixing these issues. 

Thank you again for creating this awesome plugin. 

\* My team is conducting academic research on Java Cryptography API based misuse using your tool.

**Comment by h3xstream** [comment]
As mention previously #559.
We are more focus on finding vulnerabilities from developers with good intention.

At the moment, we are only focusing at finding empty host verification (low false positive). But it is true that they are susceptible to logic flaws and small details matter.

**Comment by h3xstream** [comment]
If you have a list of common implementation mistakes in X509TrustManager, I would be interested.
