### ISSUE TITLE
Is there a way to load custom sources?

### ISSUE THREAD

**Issue by aabashkin** [find-sec-bugs/find-sec-bugs#562]
Is there a way to load custom sources in addition to custom sinks? 

I read on the wiki that one can use -Dfindsecbugs.taint.customconfigfile=/my/config/custom_sink.txt to load custom sinks. Is there a similar option for custom sources as well?

**Comment by h3xstream** [comment]
This is not a feature I have use greatly.. (outside of basic testing)

You should be able to define TAINTED sources in the same file.

Here is a quick example of Jetty API for source parameters:
https://github.com/find-sec-bugs/find-sec-bugs/blob/2340b90bc3993a595011e1cce20982533799cc0d/findsecbugs-plugin/src/main/resources/taint-config/jetty.txt#L4-L16

**Comment by h3xstream** [comment]
Here is another example: 
https://github.com/liferay/liferay-central-test-1/blob/master/modules/third-party/com-h3xstream-findsecbugs/src/main/resources/liferay-config/liferay.txt

It defines in the same file : sources, sinks and taint transfer.

 - source are application intput
 - sink are risky API
 - taint transfer: data go through those API. In some case, they can make the output safe or just transfer the state from specific input parameters.
