### ISSUE TITLE
IntelliJ Plugin and Tutorial Updates

### ISSUE THREAD

**Issue by wnyffenegger** [find-sec-bugs/find-sec-bugs#578]
The IntelliJ plugin is no longer available, at least under the name provided in the tutorial. Perhaps the plugin is not compatible with newer versions of IntelliJ?

![Screen Shot 2020-08-19 at 9 59 56 AM](https://user-images.githubusercontent.com/19293463/90654214-c1103480-e205-11ea-8bff-8f5479a3e29e.png)

The only plugin available that looks similar is called SpotBugs.

![image](https://user-images.githubusercontent.com/19293463/90654240-ca010600-e205-11ea-80a3-ea5e1b900b4a.png)

**Comment by h3xstream** [comment]
I will test it in a moment.

It should the one. Findbugs-IDEA had major limitation mainly regarding the support for Java 11+.

**Comment by h3xstream** [comment]
I will update the screenshot in the tutorial at the same time.

The screenshots on the website also needed a refresh..

**Comment by scottcc** [comment]
bump

**Comment by saqibameen** [comment]
Any updates on this? I can't seem to find it still.

**Comment by saqibameen** [comment]
For those still struggling w getting FindSecBugs to work with SpotBugs, just install the SpotBugs plugin, go to preferences, search for SpotBugs there. Once you are in the settings for SpotBugs, you can simply add FindSecBugs plugin there to get it working.

**Comment by h3xstream** [comment]
The tutorial was updated to reflect the latest version of the plugin and the IDE UI update.

https://github.com/find-sec-bugs/find-sec-bugs/wiki/IntelliJ-Tutorial

**Comment by h3xstream** [comment]
Let me know if I am missing anything.
