### ISSUE TITLE
Where to contribute framework specific contributions?

### ISSUE THREAD

**Issue by pmlopes** [find-sec-bugs/find-sec-bugs#584]
This project already supports many detectors, some are generic enough that can be extended just by adding extra metadata to config files. One specific case is the password detection.

As a developer (and user) of a framework not covered in the current code, what would be the best place to make such contribution?

I can enumerate all places in https://github.com/eclipse-vertx/vert.x/ and https://github.com/vert-x3 modules where passwords are accepted and add them to: https://github.com/find-sec-bugs/find-sec-bugs/blob/master/findsecbugs-plugin/src/main/resources/password-methods/password-methods-all.txt

Would that be the right place? Or should I extend the current detector and override the default listing file for the specific framework?

**Comment by h3xstream** [comment]
The configuration file [password-methods-all.txt](https://github.com/find-sec-bugs/find-sec-bugs/blob/master/findsecbugs-plugin/src/main/resources/password-methods/password-methods-all.txt) should be the place to add the new API. If there is a huge number of API then we could consider creating a separate file.

# Intuitive password detector

Keep in mind, there is [one detector](https://github.com/find-sec-bugs/find-sec-bugs/blob/master/findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/password/IntuitiveHardcodePasswordDetector.java) detecting potential hardcoded password only based on the method name alone regardless of the class name. It will find plenty of private API we don't know about (using `setPassword`). It will also catch plenty of API from popular framework. You will still find API like the one below. These were had prior to this detector.
 - `org/springframework/security/oauth2/config/annotation/builders/ClientDetailsServiceBuilder$ClientBuilder.secret(Ljava/lang/String;)Lorg/springframework/security/oauth2/config/annotation/builders/ClientDetailsServiceBuilder$ClientBuilder;#0`
 - `javax/security/auth/callback/PasswordCallback.setPassword([C)V#0`

## Vert.x

The following API should already be covered.

```java
Trust<JksOptions> SERVER_JKS = () -> new JksOptions().setPath("tls/client-truststore.jks").setPassword("wibble")
```
```java
ProxyOptions proxyOptions = new ProxyOptions();
proxyOptions.setUsername("guess").setPassword("guess");
```

**Comment by pmlopes** [comment]
Ok great, I'll first asses if all places where passwords are used can be matched to the `IntuitivePasswordDetector` and only if we have irregularities I'll propose them to the `password-methods-all.txt`
