### ISSUE TITLE
Semgrep rules vs sonar rules

### ISSUE THREAD

**Issue by javixeneize** [find-sec-bugs/find-sec-bugs#585]
Hi

Im analysing my code both with findsecuritybugs as a sonar plugin and as a semgrep package.

It has a http request with a Delete verb, and semgrep detects it as a sql injection, which clearly is a false positive. However, when scanning it with sonar, it doesnt detect that problem.

Are rules for sonar and semgrep different? 

Thanks

**Comment by h3xstream** [comment]
Using the DELETE method is not a vulnerability by itself.

My guess would be that "semgrep" confused a string with the keyword DELETE for an SQL query.

**Comment by javixeneize** [comment]
I agree with your views but I understood it was your rule the one that was guiding to this false positive. I will contact them

The code is something that anybody can write, just a http method with the delete verb.

So, are the rules for semgrep and sonar the same then?

Thanks

**Comment by h3xstream** [comment]
I don't think they are reusing our rules directly.

It is likely that they will cover some area we don't and vice versa.

**Comment by javixeneize** [comment]
I thought those rules were written by you and adapted to their engine. Makes sense then. Thanks for the clarification

**Comment by javixeneize** [comment]
Hi

FYI - This is the issue i open to semgrep guys. It contains the code snippet that triggers the FP

https://github.com/returntocorp/semgrep-rules/issues/819
