### ISSUE TITLE
Using find sec bugs via mvn

### ISSUE THREAD

**Issue by siewer** [find-sec-bugs/find-sec-bugs#596]
Is it possible to use maven plugin to fire find security bugs like spotbugs? Eg mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs ?

**Comment by h3xstream** [comment]
I don't think it is possible to pass configuration to add find-security-bugs in the active plugins.

If you are objective is to avoid editing `pom.xml` file.
You can configure [a special profile in your `settings.xml`](https://maven.apache.org/settings.html) and enable this profile whenever you need to do a scan.
