### ISSUE TITLE
Scanning Kotlin doesnt work with gradle-plugin

### ISSUE THREAD

**Issue by David-OliverM** [find-sec-bugs/find-sec-bugs#598]
| Component          | Version|
| ------------------ | ------- |
| Gradle                  |  4.0.1   |
| Java                     |   1.8     |
| SpotBugs             |  4.1.2   |
| FindSecBugs        |  1.10.1  |

## Problem

According to https://github.com/find-sec-bugs/find-sec-bugs/issues/500#issuecomment-524417421 findsecbugs is Kotlin-ready.
But in my case it isn't giving any output when analysing my Kotlin project. It is analysing the java files but not the kotlin files. I created a java file and a kotlin file with the exact same Bug. It finds the Bug in the java file but not in the kotlin file.
Im using the Gradle-plugin to scan my Android Project.

**Comment by h3xstream** [comment]
This is something to ask to the Gradle plugin : https://github.com/spotbugs/spotbugs-gradle-plugin

**Comment by David-OliverM** [comment]
Hi,
thanks fro the reply!
