### ISSUE TITLE
Please push tag for 1.11.0

### ISSUE THREAD

**Issue by pzygielo** [find-sec-bugs/find-sec-bugs#612]
https://repo.maven.apache.org/maven2/com/h3xstream/findsecbugs/findsecbugs-plugin/1.11.0/

**Comment by h3xstream** [comment]
The tag will be add in a moment along with the release notes.

**Comment by pzygielo** [comment]
Thanks. Tag looks fine, but perhaps you'd like to synchronize tag with [RN](https://github.com/find-sec-bugs/find-sec-bugs/releases/tag/version-1.11.0) title?
![rn](https://user-images.githubusercontent.com/11896137/98161428-05939e00-1ee0-11eb-809e-06913fc1969d.png)
