### ISSUE TITLE
IMPROPER_UNICODE Missing from Documentation

### ISSUE THREAD

**Issue by kev22257** [find-sec-bugs/find-sec-bugs#613]
It appears that the [documentation](https://find-sec-bugs.github.io/bugs.htm) for the detectors does not include anything for [IMPROPER_UNICODE](https://github.com/find-sec-bugs/find-sec-bugs/blob/5599c3ee68089ecefff47619412be628f1cf5dff/findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/ImproperHandlingUnicodeDetector.java#L38).  Is this correct?  We build our application daily and just started seeing errors for this issue (we build with RELEASE and I see 1.11.0 was released today).  It's unclear what the "bug" is and what the expected resolution should be.

**Comment by kev22257** [comment]
It if helps you can see the metadata was updated and the same information that is missing from the website can be found [here](https://github.com/find-sec-bugs/find-sec-bugs/blob/5599c3ee68089ecefff47619412be628f1cf5dff/findsecbugs-plugin/src/main/resources/metadata/messages.xml#L6430).

**Comment by h3xstream** [comment]
https://github.com/find-sec-bugs/find-sec-bugs.github.io/commit/a713b8365dc489f8d3108ac40d199556aefb2545
