### ISSUE TITLE
Could not find an "-exclude" flag for files and directories in the CLI wiki

### ISSUE THREAD

**Issue by robwillup** [find-sec-bugs/find-sec-bugs#619]
## Description

In the CLI documentation, I could not find an option to exclude files/directories from analysis. For example:

```bash
# only analyze .class files
./findsecbugs.sh -excludeFromAnalysis *.jar ../my-app
```

If this option does not exist, it could be interesting in cases when we just want to scan certain file types and we have different files in the same base directory.

**Comment by h3xstream** [comment]
The easiest way would be to build a list of jar that you need (with the exclude that you want) and redirect the list to `findsecbugs.sh` script.

Something like this:
```
find ../my-app -name "*.jar" | awk '!/exclude1/ && !/exclude2/' | findsecbugs.sh -xargs -progress -html -output report.htm
```
Ref: https://github.com/find-sec-bugs/find-sec-bugs/wiki/CLI-Tutorial#scanning-multiple-jars

**Comment by robwillup** [comment]
Thank you @h3xstream !

That works well 👍🏼
