### ISSUE TITLE
Filter configuration is silently ignored

### ISSUE THREAD

**Issue by zabbal** [find-sec-bugs/find-sec-bugs#623]
## Environment

| Component          | Version |
| ------------------ | ------- |
| Maven              | 3.6.3   |
| Gradle             | -   |
| Java               | 1.8.0_282   |
| SpotBugs           |  4.2.0  |
| FindSecBugs        |  1.11.0  |

## Problem

The filter configuration is ignored without any error in the logs. The default spotbugs findings are shown - as if no filters were configured at all.

## Code (If needed)

The pom.xml addition:

```
<build>
    <plugins>

      <plugin>
				<groupId>com.github.spotbugs</groupId>
				<artifactId>spotbugs-maven-plugin</artifactId>
				<version>4.2.0</version>
        <configuration>
          <effort>Max</effort>
          <threshold>High</threshold>
          <xmlOutput>true</xmlOutput>
          <failOnError>false</failOnError>
          <includeFilterFile>spotbugs-security-include.xml</includeFilterFile>
          <excludeFilterFile>spotbugs-security-exclude.xml</excludeFilterFile>
          <plugins>
            <plugin>
              <groupId>com.h3xstream.findsecbugs</groupId>
              <artifactId>findsecbugs-plugin</artifactId>
              <version>1.11.0</version>
            </plugin>
          </plugins>
        </configuration>
			</plugin>

    </plugins>
  </build>
```
The filter files:
spotbugs-security-include.xml:
```
<FindBugsFilter>
  <Match>
    <Bug category="SECURITY"/>
  </Match>
</FindBugsFilter>
```
spotbugs-security-exclude.xml:
```
<FindBugsFilter>
</FindBugsFilter>
```

**Comment by h3xstream** [comment]
The request make perfect sense. Failing silently is a bad thing a QA tool. [You can open aticket here](https://github.com/spotbugs/spotbugs-maven-plugin/issues).

Personnally, I am using the format `<includeFilterFile>${session.executionRootDirectory}/spotbugs-security-include.xml</includeFilterFile>` to be sure it pick the configuration at the root of my project regardless of submodule.
