### ISSUE TITLE
messages.xml: Wrong solutions for XXE_XSLT_TRANSFORM_FACTORY

### ISSUE THREAD

**Issue by ecki** [find-sec-bugs/find-sec-bugs#638]
https://github.com/find-sec-bugs/find-sec-bugs/blob/fa7f7c4d43f178bf8e2062a35d5d66214fe88965/findsecbugs-plugin/src/main/resources/metadata/messages.xml#L1794

The rule XXE_XSLT_TRANSFORM_FACTORY suggests two solutions, the heading for the two solutions is confused (the FSP solution is below the 

Also the solution for turning off external DTDs is totally missleading, it tells users to use `"all"` instead of `""`.

**Comment by h3xstream** [comment]
Could catch I see that the change is need for both XXE_XSLT_TRANSFORM_FACTORY  and XXE_DTD_TRANSFORM_FACTORY

**Comment by h3xstream** [comment]
I double check and we are detecting the right patterns. Empty strings only are consider safe to disable reference to external resources.

https://github.com/find-sec-bugs/find-sec-bugs/blob/3d5601a4cee9ada763dd3605b1a4882c7c248aaa/findsecbugs-samples-java/src/test/java/testcode/xxe/transformerfactory/TransformerFactorySafe.java#L69-L73

**Comment by h3xstream** [comment]
I notice the title for the solution were also reverse.
Everything should be fix in #641
