### ISSUE TITLE
CLI does not support kotlin

### ISSUE THREAD

**Issue by hackthesoul** [find-sec-bugs/find-sec-bugs#647]
## Environment

| Component          | Version |
| ------------------ | ------- |
| SpotBugs           | 4.1.4 |
| FindSecBugs        | 1.11.0 |

## Problem

It does not scan *.kt files with cli mode

## Code (If needed)

![image](https://user-images.githubusercontent.com/59822000/128009206-cf090ff1-8db9-4038-bbbe-4a8c946276ac.png)

Could you verify it?

**Comment by h3xstream** [comment]
The CLI interface is not giving a obvious error message but basically their are no **bytecode** classes to scan.
You can either provided classes (.class) or jar files as input.

(Maven, Gradle and IDE integration are building behind the scene your source files.)

**Comment by hackthesoul** [comment]
I got it. Thanks for your reply!
I will try with jar file
