### ISSUE TITLE
CWE/SANS Top 25

### ISSUE THREAD

**Issue by HuaYangFu** [find-sec-bugs/find-sec-bugs#649]
I need this feature (＞x＜)  CWE/SANS Top 25

**Comment by h3xstream** [comment]
If you look at the main configuration file for the plugin (findbugs.xml), you will find CWE mapping for all bug patterns.
Informational findings that do not represent vulnerability have no CWE mapped.

**Comment by h3xstream** [comment]
While almost all bug already had a mapping I look at the configuration to verify if some CWE mapping could be added. I even found [a typo](https://github.com/find-sec-bugs/find-sec-bugs/commit/1e1d203d0491984bc2cb70b87106de655b61be7a#diff-4bb0914b8892a1aa7767db972707f46afa8218577bd44a602ef898b560877d23R258).

Let me know if  you have suggestion for additionnal CWE mapping or if your use case is not met.

**Comment by h3xstream** [comment]
The CWE information is available in the file `findbugs.xml` https://github.com/find-sec-bugs/find-sec-bugs/blob/master/findsecbugs-plugin/src/main/resources/metadata/findbugs.xml
