### ISSUE TITLE
So it was cause by bytecode generated by Aspect Oriented Programming (something like AspectJ) ?

### ISSUE THREAD

**Issue by j0ck66** [find-sec-bugs/find-sec-bugs#665]
So it was cause by bytecode generated by Aspect Oriented Programming (something like AspectJ) ?

_Originally posted by @h3xstream in https://github.com/find-sec-bugs/find-sec-bugs/issues/617#issuecomment-747259018_

**Comment by j0ck66** [comment]
So is it possible to solve the problem

**Comment by h3xstream** [comment]
I have reopen the original thread : #617
