### ISSUE TITLE
Interprocedural Taint Analysis?

### ISSUE THREAD

**Issue by baloghadamsoftware** [find-sec-bugs/find-sec-bugs#675]
Sorry, this is not really an issue, but rather a discussion. (Maybe FindSecBugs could have a "Discussions" tab similar to [SpotBugs](https://github.com/spotbugs/spotbugs/discussions).

One of the main features of FindSecBugs is the taint analysis which is missing from basic SpotBugs. However, our tests confirmed that taint analysis works inside a single method only. Thus if one method reads tainted data and passes this data as a parameter to another method which then uses this data in a dangerous way then no warning is given. I wonder whether it is possible to implement a mechanism (probably a detector prerequisite to all taint detectors) which propagates taint information betweenn methods. Or are we wrong with out tests and does interprocedural taint analysis already exists?

**Comment by topolik** [comment]
Hi @baloghadamsoftware,

Yes, the taint analysis of FSB is intraprocedural only with some enhancements. However, when an `UNKNOWN` data enters a sink there should be always some warning generated. The warning is not generated only when `SAFE` data enters a sink. If that's not the case please create an issue!

I tried to implement full interprocedural analysis into FBS twice. So far the only working solution was to extend it to cover class static initializer and class fields, which is merged into FSB. 

Having full interprocedural context-sensitive analysis requires more work/time/knowledge than I currently have. My main obstacle was the memory/CPU consumption when merging taint frames. Each frame needs a separate object model (tree of objects) in the memory. It can grow really fast considering full context (ThreadLocals and static vars) and it's not needed usually. There is usually a lot of unknown classes and paths considering modern web apps / frameworks so the context is never complete. On top there is no data labeling right now coming out from the known DFD + CFG so also memory model of dead branches is included after each method analysis (e.g. `i = 1; if ( i == 0) A() else B()`). For this to be practically usable it requires more work to be done.
