### ISSUE TITLE
how can i modify the severity

### ISSUE THREAD

**Issue by TimerZz007** [find-sec-bugs/find-sec-bugs#694]

**Comment by TimerZz007** [comment]
i want modify the severity and the solution for some of rules，but i do not know how to do that… is anybody can give me some suggestions，thanks a lot！

**Comment by h3xstream** [comment]
Severity (or Priority : Low, Medium, High) is not static in a configuration files. It will vary based on the code context. Most injection are rated medium by default but it become high if the source leading to the sink is tainted (confirmed user-input). It can also be set to low if an incomplete/ slightly risky encoding options is found.

SQL injection is one example.
https://github.com/find-sec-bugs/find-sec-bugs/blob/e8c41d2109b542a8506fa40e63519a1ca78e2a43/findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/sql/SqlInjectionDetector.java#L42-L50

**Comment by TimerZz007** [comment]
okay,i get it, thanks
