### ISSUE TITLE
SpotBugs Report Metrics result

### ISSUE THREAD

**Issue by chihhung1016** [find-sec-bugs/find-sec-bugs#714]
In the Metrics section of the SpotBugs Report HTML, vulnerabilities have been detected, yet it shows "0 lines of code analyzed, in 0 classes, in 1 packages." What does this mean?

**Comment by h3xstream** [comment]
The metrics are computed by SpotBugs. The number of classes to zero should be an indicator that SpotBugs didn't have access to any compiled classes.

It could be that the project was not compiled.
It could also be that classes are not at the expected location.
