### ISSUE TITLE
Java 21 Support

### ISSUE THREAD

**Issue by Jeeppler** [find-sec-bugs/find-sec-bugs#723]
## Description

Support [Java JDK 21](https://jdk.java.net/21/). The release of Java 21 is the next long term support release.

I am willing to help implement it, but I would like to have some directions on how to get started.

**Comment by haerter-tss** [comment]
Any updates on this issue? When are you planning to support java 21?

**Comment by gtoison** [comment]
Have you encountered issues with Java 21?
SpotBugs is regularly tested with JDK 21 and it runs fine, I suppose that the find-sec-bugs plugin should work for the most part

**Comment by Jeeppler** [comment]
SpotBugs does support JDK 21, but FindSecBugs does use an old version of SpotBugs. In essence, FindSecBug needs a new release to support Java 21.

**Comment by gtoison** [comment]
I think it's normally the other way around: SpotBugs runs and uses FindSecBugs as a plugin
So what matters is the SpotBugs version you're using, plugins such as FindSecBugs will not override that version

Or maybe there's a way to run FindSecBugs standalone?

**Comment by Jeeppler** [comment]
Yes, the problem is with the standalone version.

If you go to the latest [FindSecurityBugs release 1.12.0](https://github.com/find-sec-bugs/find-sec-bugs/releases/tag/version-1.12.0) and download the `findsecbugs-cli-1.12.0.zip` you will end up with the following structure:

~~~
user@pc:~/findsecbugs-cli-1.12.0$ tree
.
├── findsecbugs.bat
├── findsecbugs.sh
├── include.xml
└── lib
    ├── asm-9.2.jar
    ├── asm-analysis-9.2.jar
    ├── asm-commons-9.2.jar
    ├── asm-tree-9.2.jar
    ├── asm-util-9.2.jar
    ├── bcel-6.5.0.jar
    ├── commons-lang3-3.12.0.jar
    ├── commons-text-1.9.jar
    ├── dom4j-2.1.3.jar
    ├── findsecbugs-plugin-1.12.0.jar
    ├── gson-2.9.0.jar
    ├── jaxen-1.2.0.jar
    ├── jcip-annotations-1.0.jar
    ├── jsr305-3.0.2.jar
    ├── Saxon-HE-10.6.jar
    ├── slf4j-api-1.8.0-beta4.jar
    ├── spotbugs-4.6.0.jar
    └── spotbugs-annotations-4.6.0.jar

1 directory, 21 files
~~~

As you can see it contains `spotbugs-4.6.0.jar` as a dependency. The latest SpotBugs version is: 4.8.3. Therefore the Java 21 issue is probably resolved by just upgrading the dependencies.

**Comment by gtoison** [comment]
Thanks for clarifying, I'm not sure how it ended up with SpotBugs 4.6.0 because the dependencies are on 4.5.3
I have submitted a PR to update SpotBugs to 4.8.3
